### ISSUE TITLE
Feature Request: Start Robocopy as another user

### ISSUE THREAD

**Issue by mrichman** [tjscience/RoboSharp#10]
I have cases where I need to start Robocopy under another user's identity. Could you add an option to RoboCommand.cs so that `process.StartInfo` can accept Username and Password options?

Thanks!

**Comment by mrichman** [comment]
Sent you a pull request.

**Comment by tjscience** [comment]
If you have time you can add it and I will merge it later. If not, I may be able to get to it later today.

**Comment by mrichman** [comment]
I added it here: https://github.com/mrichman/RoboSharp/pull/1

For now, I've created my own NuGet package which I'm referencing until you're able to merge my pull request and update your public NuGet package to 1.1.0.
