### ISSUE TITLE
Get In-Progress File Name

### ISSUE THREAD

**Issue by RFBomb** [tjscience/RoboSharp#100]
I have made a wrapper for this project for my current application. The wrapper creates a RoboSharp object with all the defaults, provides the `<summary>` text that the Nuget package for some reason doesn't, and provides a few methods for binding and updating progress bars and labels while the task is running. 

I have a created a progress bar that can display the current file progress, but I can't see any way to get the current file name. I believe the current setup only provides a filename in the GetResults() function, or on the FileCompleted event. 
What I'm planning to do is update a progress bar with the current file progress while displaying the filename being copied. 

Can a the current file name / paths be added to the EventArgs for the CurrentFile Progress event? Maybe include a ProcessedFile object into the EventsArgs (but maybe rename to CurrentFile to avoid confusion - looking at the ProcessedFile class it doesn't seem to matter though, since its just basic info about the file)

(I have no problem working to implement this and submitting a pull request, but was wondering if this is the best method for getting this information, if it doesn't exist currently, I'll just need a push in the right direction if thats what we want to do.)

Secondary question: 
I'm hoping to implement an 'Overall Progress' bar. The only way I currently see to do this is to run once as ListOnly = true, grab the total number of files, then run a second time to run the copy command, then increment a counter after OnFileCompleted event and divide by the ListOnly filecount. I believe that is the only way to (accurately) do this, correct? The total file count isn't attained until it completes atleast one run right?

**Comment by PCAssistSoftware** [comment]
Thanks, will have a proper look when I have more time.

I have my own wrapper I also use for similar purposes - the current file name is already available in the OnFileProcessed event by looking at e.ProcessedFile.Name for the name and can also get size from e.ProcessedFile.Size

For overall progress I do what you suggested I run as listonly to get file / directory count and total size and then update progress bars based on those results - works perfectly well for me

**Comment by RFBomb** [comment]
I was under the impression that the ‘OnFileProcessed’ event only runs once a file reaches 100% completion, and subsequently returns the completed filename, not the current in-progress/next filename. 

IE, that would be good for logging completed files, not displaying filename of a large file in progress. 

Also, regarding settings robocopy to use multiple threads: how does that interact with the event that reports file progress? ( if 3 threads allows copying three files at once, will it report fire an event each time one of those threads updates?  Or is it 3 threads copying 1 file, which IMO doesn’t make a whole lot of sense. I guess this is more of a general robocopy question than robosharp)

**Comment by PCAssistSoftware** [comment]
From the testing I have done with my wrapper (which has been in use for a long time now and used for some big jobs migrating user profiles and data to new servers) it is retrieiving the current file that is copying as definitely when setting it to copy big test files such as ISO files for example it shows correct file name and also show progress size of that current file along with overall progress.

I don't use MT switch with RoboSharp as causes lots of issues with counts for directories and figures shown for bytes copied overall and totally broke file copy progress.  Also from testing it didn't actually improve performance when using in RoboSharp in same way it does if using RoboCopy from command line

**Comment by RFBomb** [comment]
This is all good info. I appreciate it. 

If the OnFileProcessed event is reporting current file name, are you only incrementing an overall progress bar when a name change is detected (processing it in the event method)? 

This also sounds like it might be triggering the OnFilePorcessed event multiple times per file. Which is counter intuitive to my first impression   

Looks like I’ll have to do some testing myself with large files

**Comment by PCAssistSoftware** [comment]
No problem at all, spent ages writing and tweaking my wrapper to show as much useful information as I could, played with so many different ways to try and get overall progress working as I needed.

Would be interested to know results of your testing in case I have got it wrong etc then we can work together to ensure it all works as we want.

**Comment by RFBomb** [comment]
As long as I'm not traveling for work next week, I'll finish up the small rework stuff I have to do to my project and whip up a test method  for it.  I should be able to start testing later monday

**Comment by tjscience** [comment]
Is this still an issue?

**Comment by RFBomb** [comment]
I apologize, as I had been pulled away from that portion of my project and
haven’t been able to test like I said I would try to.

But tomorrow I have some time in house I should be able to review my
original question here and follow up with it. (This segment of my project
is framed in, but incomplete and needs doing anyway).

**Comment by RFBomb** [comment]
OK, so I finally got around to testing this. Here is what I'm seeing:
My 
The binding command and the corresponding function are below:
For reference, I am copying from a folder on the computer to the root of a USB stick, not that should should make a significant difference.

```
//Note This code is set up on a self-contained form that just has a simple button to start the test, a progress bar, and a listbox for showing filenames.

public void SetupRoboCopy 
{
        // cmd is my wrapper class, which contains the RoboSharpObject this class provides.
        .....
        cmd.RoboSharpObject.OnFileProcessed += RoboSharpObject_OnFileProcessed;        
        cmd.RoboSharpObject.OnCopyProgressChanged += RoboSharpObject_OnCopyProgressChanged;
        .....
        await cmd.RoboSharpObject.StartAsync();
}
private void RoboSharpObject_OnFileProcessed(object sender, RoboSharp.FileProcessedEventArgs e)
{
        Action action = new Action(() =>
                {
                    FilesProcessed++;
                    this.ProgressBar_1.Value = (int)((this.FilesProcessed / this.TotalFiles) * 100);
                    LBFiles.Items.Add(e.ProcessedFile.Name);
                });
                if (e.ProcessedFile.FileClassType == RoboSharp.FileClassType.File)
                    this.Invoke(action);
}
private void RoboSharpObject_OnCopyProgressChanged(object sender, RoboSharp.CopyProgressEventArgs e)
{
        double progress = e.CurrentFileProgress;
}
```

As the task runs, the events are seemingly called AFTER completion of the task. As in, while I'm watching the USB stick on one screen and have the breakpoints in VS on another screen, the breakpoints are not hit until all files have been copied to USB. 

First `OnFileProccessed` is triggered, providing the filename, then `OnCopyProgressChanged` is triggered. The problem I'm seeing is that OnCopyProgressChanged is only ever providing a value of 100% complete.  This was also using a 600MB file and USB2.0, so it took about 20 seconds to copy the file in.

So, it would seem that robocopy finishes its run, then the output is parsed and relayed to the program as events. So it is not real time logging as it would seem. Which also makes me curious the start/stop/pause functions work. (I haven't tested these yet)

edit: More testing completed. 
This time, I tried updating the progress bar based on the copy progress of the 600MB file.
the `OnCopyProgressChanged` event does not fire until the copy operation is complete, at which point the resulting object is showing 100% complete.

**Comment by RFBomb** [comment]
Followup testing after reading the comments regarding using a single instead of a multi-thread:

- Settings Threads = 1, 3 files totaling 1.24GB 

- For files less than 400MB being copied to a USB2.0 stick, the `OnCopyProgressChanged` reported 100% as the first report for every file, per my comment and testing above, which was using 3 threads.
- For files larger than 400MB, I was able to catch between  3 and 5 times that it updated the progress on the current file. Typically the values were somewhere around 0-15%, 50-90%, and a guaranteed one at 100%. 
- Typically when the file exceeded 75% completion or greater, there were no more updates to the progress bar until it hit 100% on the file, which was several seconds. 

Once again, `OnFileProcessed` would trigger prior to  `OnCopyProgressChanged`. So it appears that the current file being processed if the one that shows up in the `FileProcessedEventArgs`. 

I was originally under the assumption based on 'Processed' being past-tense that this would trigger after file processing was complete, not that it would occur when it switched to the next file. I still think for clarity, if possible, it may be worthwhile to have the current file as part of the `CopyProgressEventArgs`. 

So, running single threaded I think I can manage to get it to do what I want to do, now that I understand the two events much better. Here is my remaining question:
- Is there some specified interval (time or progress?) that it spits out the progress event? or is it just whenever robocopy decides to spit it out?
