### ISSUE TITLE
Unicode characters from Process

### ISSUE THREAD

**Issue by JoE-Seeve** [tjscience/RoboSharp#103]
Special characters of a language (for me the special characters of the German language) are not returned by RoboSharp in the different events.

The following could help to solve this (RoboCommand.cs - Start):

 process.StartInfo.StandardOutputEncoding = System.Text.Encoding.GetEncoding(CultureInfo.CurrentCulture.TextInfo.OEMCodePage);

**Comment by RFBomb** [comment]
Should be resolved
