### ISSUE TITLE
strongly-named assembly is required

### ISSUE THREAD

**Issue by RFBomb** [tjscience/RoboSharp#114]
Could not load file or assembly 'RoboSharp, Version=1.2.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

https://stackoverflow.com/questions/290980/error-a-strongly-named-assembly-is-required

The NuGet package is not signed, meaning anyone using it cannot sign their packages.
Would it be possible to have this signed? 
(This is not mission-critical for me, as I could always compile the repo and sign it myself, but using the nuget would be nice)

**Comment by PCAssistSoftware** [comment]
Will let @tjscience answer that one as an ongoing cost involved in having a code signing certificate.  I have one myself and just sign it along with my .EXE when creating apps.

Although to be fair I have used RoboSharp in many applications unsigned and never had an issue

**Comment by RFBomb** [comment]
Yea, I'm currently using it unsigned, and since this is an internal company application It shouldn't be an issue. Plus, anyone using the library can also pull the repo and sign it themselves. But I figured it was atleast worth noting

**Comment by saufdermaur** [comment]
Hello and thanks for this library!

I'm considering using it in a project, but strong naming is enabled on the affected assembly. I noticed that the RoboSharp assembly is not currently signed.

Are you planning to provide a strongly-named version of the assembly in the near future?

Thanks again!

**Comment by PCAssistSoftware** [comment]
Not something I had planned - as per previous answer personally I just sign it myself with my code signing certificate for any apps I want to include it with

**Comment by RFBomb** [comment]
Its pretty trivial to add a signing key for this, so its a +1 from my viewpoint. (Not something I'd be able to commit anytime soon, and it doesn't affect me tho, since I'm wrapping this library and thus signing this and my wrapper in my own internal nuget)

**Comment by PCAssistSoftware** [comment]
> Its pretty trivial to add a signing key for this, so its a +1 from my viewpoint. (Not something I'd be able to commit anytime soon, and it doesn't affect me tho, since I'm wrapping this library and thus signing this and my wrapper in my own internal nuget)

Will take a look at some point, like you I am not affected as I sign the code I am using the library with anyway

**Comment by PCAssistSoftware** [comment]
Been reading up on this, and seems to be mixed opinions on whether it should be done or not, so perhaps requires some further discussion at some point - https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md
