### ISSUE TITLE
Backup App - source and destination paths not working as expected when entering root paths with slashes

### ISSUE THREAD

**Issue by PCAssistSoftware** [tjscience/RoboSharp#117]
New issue created following discussions in #117 which veered off on to similar but unrelated areas

@JoE-Seeve had problems such as not working when entering source and destination paths with trailing slashes e.g. E:\ rather than E:

----------------------------------------------

Original posts copied below:-

The copy job shown in the following figure is copiying something but not as expected.
![grafik](https://user-images.githubusercontent.com/92209494/144755845-ee0f181b-c747-422e-b291-9d28e6e0f38f.png)

_Originally posted by @JoE-Seeve in #116 - and moved here to create separate issue_

**Comment by PCAssistSoftware** [comment]
Okay - I see your point....

Hadn't noticed it before as I don't use the included Backup App I use my own GUI and that works fine and doesn't have same issue, and for life of me I cannot see difference between how that app does it and how my app does it e.g. if I type in my app source box E: or E:\ it works fine either way as path gets the trailing \ removed, and all I am doing is setting .Source to text box content in same way.....

But in Backup App if I put breakpoint on line 62 I can see the value of copy.CopyOptions.Source is getting set to E:\ even though textbox shows E:\ - so somewhere it is adding an extra \ to the end - not sure if this is a C# thing as seeing it as an escape character? as my app is in VB - but that I belive could be issue.

**Comment by PCAssistSoftware** [comment]
> ... and here are additional tests with the BackupApp. I want to copy the "C:\" to "E:\" (/MIR). The problem @PCAssistSoftware has described occur (source: "C:", "C:", C:\\"). ![grafik](https://user-images.githubusercontent.com/92209494/144758076-7ebe66a3-13b8-4125-99be-dffb16210161.png)
> 
> As a described before the correct copy job will be done with source "C:\temp\.." because this points to C:\ and not to the start directory. The name of the directory which was given here as "temp" does not matter. ![grafik](https://user-images.githubusercontent.com/92209494/144758093-4d1d4951-43fa-4103-9540-3e5a7c244c81.png)

**Comment by JoE-Seeve** [comment]
The problem occurs with all applications, including my app, when I want to copy a root directory and use a directory selection dialog to specify a standard root directory as the source (e.g. "C: \"). I don't know why a new issue was opened here because it's exactly the same problem that was addressed in # 116!

**Comment by PCAssistSoftware** [comment]
Surely c:\temp\... wouldn't work with RoboCopy either as it is not a valid source directory - does it work with c:\temp  ?

**Comment by PCAssistSoftware** [comment]
> The problem occurs with all applications, including my app, when I want to copy a root directory and use a directory selection dialog to specify a standard root directory as the source (e.g. "C: "). I don't know why a new issue was opened here because it's exactly the same problem that was addressed in # 116!

As I had replied in previous issue it works perfectly fine with my app (VB.NET) when either entering C:\ or C: or when using a directroy selection dialog to choose a root of a drive - hence suggestion that perhaps issue is related to example Backup App or perhaps C#?  (this is assuming your app is C#?).  In VB.NET however I enter the path the trailing slash is removed and backup job works fine.

As above reply

> But in Backup App if I put breakpoint on line 62 I can see the value of copy.CopyOptions.Source is getting set to E:\ even though textbox shows E:\ - so somewhere it is adding an extra \ to the end - not sure if this is a C# thing as seeing it as an escape character? as my app is in VB - but that I believe could be issue.

**Comment by PCAssistSoftware** [comment]
> I don't know why a new issue was opened here because it's exactly the same problem that was addressed in # 116!

The problem in #116 had no relation to slashes whatsoever - it was to do with choosing a root path as source which was same drive as app was running from

**Comment by PCAssistSoftware** [comment]
This may perhaps be relevant to the trailing quote issue, quote below from https://ss64.com/nt/robocopy.html - and does seem to be to do with escape character as I thought, and would explain difference between my app written in VB.NET and the sample Backup App in the project written in C# - as in VB.NET you don't need to escape a backslash.

"If either the source or desination are a "quoted long foldername" do not include a trailing backslash as this will be treated as an escape character, i.e. "C:\some path\" will fail but "C:\some path\\" or "C:\some path\." or "C:\some path" will work."

**Comment by RFBomb** [comment]
@PCAssistSoftware 
backslashes are used as escape characters in C#. As such:
C:\ == `C:\\` 
C:\temp == `C:\\temp`
C:\temp\subfolder == `C:\\temp\\subfolder`
C:\temp\subfolder\etc == `C:\\temp\\subfolder\\etc`

So a method that wants to the last subfolder/directory from a path may look like this:

```
string X = "C:\\Some\\Path\\To\\File.txt";
int i = X.LastIndexOf('\\');          -> i will be equal to 15
return X.remove( i );   -> Returns "C:\\Some\\Path\\To"
```

**Comment by PCAssistSoftware** [comment]
@JoE-Seeve

My sincere apologies as I just think I have completely confused myself here in relation to root, trailing slashes and what the original issue / fox iwas, and therefore we are both not fully understanding each others points. 

I think the confusion partly comes from you testing with the C# sample Backup App and me using my own VB based GUI, so seeing different results due to different code etc.  

So let's perhaps close this issue and start again afresh once @RFBomb has finished his testing to fix the working directory issue in #119, then I can test that with both my app and the C# Backup App so we can see and discuss the same problem if it still exists rather than perhaps talking cross purposes and cross programming languages.

:)

**Comment by PCAssistSoftware** [comment]
@JoE-Seeve  - please test #119 and see if it resolves the issues you had - if related - thanks

**Comment by JoE-Seeve** [comment]
... as I said before, I have no problem here!

**Comment by PCAssistSoftware** [comment]
> ... as I said before, I have no problem here!

Cool, if you had issue in #117 then please test #119 to see if it fixes it

**Comment by PCAssistSoftware** [comment]
Closed, created in error due to my misunderstanding of an issue

**Comment by PCAssistSoftware** [comment]
@tjscience - please could you completely delete this issue, it was created by me due to a misunderstanding of another users issue, so content is not needed, confusing and exists in 116 anyway - thanks
