### ISSUE TITLE
Dispacher Not Available

### ISSUE THREAD

**Issue by MarkECrum** [tjscience/RoboSharp#123]
I've created a WinForms app... for the events the Dispatcher takes care of the multi-threading access to the controls... But I cannot find any reference to it with .net60. If we can't resolve this I do have a very elegant solution class written by Michael Demeersseman that can be shared.... But I would like to figure this Dispatcher thing out first if I can. Thanks guys for your help.

**Comment by RFBomb** [comment]
See https://github.com/tjscience/RoboSharp/issues/131#issuecomment-1005317766

I’ve never used a dispatcher in my few Winforms projects, simple `Control.Invoke(Action);`

All the events the objects trigger should already be handling this for you, since events are invoked always. 

What exactly are you trying to do?

**Comment by MarkECrum** [comment]
I was unaware of that call. but the issues is setting a controls.Text property... I'll read up more. Thanks for pointing me in the right direction.

**Comment by PCAssistSoftware** [comment]
Not sure if relevant to discussion - perhaps I am missing the point (quite possible!) - but if trying to update a control "across threads" so to speak then the below may help for VB.NET at least

  `Me.Invoke(Sub() TextBox1.Text("HELLO"))`

Instead of 

` TextBox1.Text("HELLO")`

or something like

```
UpdateTextBox("HELLO")

Private Sub UpdateTextBox(text As String)
        If TextBox1.InvokeRequired Then
            'We are on a secondary thread.
            TextBox1.Invoke(New Action(Of String)(AddressOf UpdateTextBox), text)
        Else
            'We are on the UI thread.
            TextBox1.Text = text
        End If
    End Sub
```

**Comment by PCAssistSoftware** [comment]
Closed as no responses
