### ISSUE TITLE
Is there a way to use this in multi-job scenario?

### ISSUE THREAD

**Issue by justind-dev** [tjscience/RoboSharp#126]
I apologize if this is not the right place to ask this question. I didnt want to spam anyone's email to ask it. What I am trying to do is re-create this powershell script in C#: https://support.zadarastorage.com/hc/en-us/articles/213024806-How-to-Run-Robocopy-in-Parallel

However I am tripping up greatly on this portion of the logic using the RoboSharp library:
$j = Get-Job -State "Running"
while ($j.count -ge $max_jobs) 
{
 Start-Sleep -Milliseconds 500
 $j = Get-Job -State "Running"
}
 Get-job -State "Completed" | Receive-job
 Remove-job -State "Completed"
Start-Job $ScriptBlock -ArgumentList $_,$src,$dest,$log
 }

Using RoboSharp, how would one grab the jobs with state "Running" or "Completed" ?

Apologies again if this is not the right place to ask this.

**Comment by PCAssistSoftware** [comment]
Hi, there is an ondoing discussion that may be partly relevant about job and job options here = 
https://github.com/tjscience/RoboSharp/issues/125

and I am currently playing with various ways of running multiple jobs - see a snippet of my code here = https://github.com/tjscience/RoboSharp/pull/107#issuecomment-997022877

**Comment by justind-dev** [comment]
Hey, thanks for the quick response I really appreciate it. I did see that before and it gave me some inspiration for my own solution. I think I actually figured out a way to do it by storing instantiated copies of RoboCommand in a list and then looping through the list. See my code here: https://github.com/justind-dev/RoboMigrator

(PSA I am a beginner with C# so you may need eyebleach afterwards :/)

**Comment by PCAssistSoftware** [comment]
Great work, will have a closer look later as may be some ideas I can use myself :)

**Comment by RFBomb** [comment]
@justind-dev  I too simply created a List<RoboCommand> and looped through it. But Work has started toward creating a Multi-RoboCommand object. I believe the core of it would be a List<RoboCommand>. Any contribution would be greatly appreciated here. #127 is a large step there to evaluating the results of a Multi-command object. 

@PCAssistSoftware #125 is something slightly different. Thats more for Saving and Loading RoboCopy parameters to disk, not running consecutive jobs.

This may be the thread to work on the Multi-RoboCommand object though.

**Comment by PCAssistSoftware** [comment]
The code I am currently using for running multiple jobs is below (still a work in progress) and this works perfectly with the excellent changes made by @RFBomb in #127 which I will hopefully merge tomorrow.

N.B. The code in Button8.click is just for testing at this stage, values will eventually be populated by browsing or entering source/destination and job name.

```
Dim RoboSharpJobsList As New List(Of RoboSharpJobs)

Dim ResultsList As Results.RoboCopyResultsList

 Private Sub Button8_Click(sender As Object, e As EventArgs) Handles Button8.Click

        AddJob("Job1", "C:\Users\darre\Desktop\1a", "C:\Users\darre\Desktop\2")
        AddJob("Job2", "C:\Users\darre\Desktop\1b", "C:\Users\darre\Desktop\2")
        AddJob("Job3", "C:\Users\darre\Desktop\1c", "C:\Users\darre\Desktop\2")

End Sub

Private Sub AddJob(name, source, destination)

        Dim job As New RoboCommand
        job.CopyOptions.Source = source
        job.CopyOptions.Destination = destination
        job.CopyOptions.CopySubdirectoriesIncludingEmpty = True
        job.CopyOptions.EnableRestartModeWithBackupFallback = True
        job.LoggingOptions.NoJobHeader = True
        job.RetryOptions.RetryCount = 2
        job.RetryOptions.RetryWaitTime = 2

        RoboSharpJobsList.Add(New RoboSharpJobs With {.Name = name, .Command = job})

        Dim lv = lvwJobs.Items.Add(name)
        lv.SubItems.Add(source)
        lv.SubItems.Add(destination)

    End Sub

 Private Async Sub btnRunJobs_Click(sender As Object, e As EventArgs) Handles btnRunJobs.Click

        ResultsList = New Results.RoboCopyResultsList

        For Each Job In RoboSharpJobsList

            Append_TextField(TextBox2, "Running: " & Job.Name)
            Append_TextField(TextBox2, Job.Command.CommandOptions)
            Append_TextField(TextBox2, "")

            AddHandler Job.Command.OnFileProcessed, AddressOf analyze_OnFileProcessed
            AddHandler Job.Command.OnCommandCompleted, AddressOf analyze_OnCommandCompleted

            Dim jobresults As RoboSharp.Results.RoboCopyResults = Await Job.Command.StartAsync()

            ResultsList.Add(jobresults)
       
        Next
     
        Dim FileResults As Results.Statistic
        FileResults = ResultsList.Total_FilesStatistic

        Dim SpeedResults As Results.SpeedStatistic
        SpeedResults = ResultsList.Average_SpeedStatistic

        Stop

    End Sub
     
Class RoboSharpJobs
   Property Name As String
   Property Command As RoboCommand
End Class
```

**Comment by RFBomb** [comment]
@justind-dev 
Please check out #128 
This new object will be what is eventually implemented into the library for running multiple robocommand jobs. Feedback (and testing) would be nice, @PCAssistSoftware  already plans on doing some of that at some point on that branch.

**Comment by justind-dev** [comment]
@RFBomb and @PCAssistSoftware 
I am finally getting around to trying to implement the awesome work you guys have done. I could really use some pointers in how to use the new features (RoboQueue, etc) You can see what I have so far here (shield your eyes, I feel like the code looks terrible but im learning):

https://github.com/justind-dev/RoboMigratorGUI/tree/RoboQueueTesting

Using that when I run, and give it a source and destination I get the following error:

```
System.ArgumentException
  HResult=0x80070057
  Message=Constructor supports only the 'Replace' action. (Parameter 'action')
  Source=System.ObjectModel
  StackTrace:
   at System.Collections.Specialized.NotifyCollectionChangedEventArgs..ctor(NotifyCollectionChangedAction action, IList newItems, IList oldItems, Int32 startingIndex)
   at System.Collections.Specialized.NotifyCollectionChangedEventArgs..ctor(NotifyCollectionChangedAction action, IList newItems, IList oldItems)
   at System.Collections.Generic.ObservableList`1.Clear() in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\RoboSharp\GenericListWithEvents.cs:line 147
   at RoboSharp.RoboQueue.StartAll(String domain, String username, String password) in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\RoboSharp\RoboQueue.cs:line 414
   at RoboMigratorGUI.Form1.<StartMigration>d__9.MoveNext() in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\Form1.cs:line 131
```

Any idea why that is based on what logic I have? I know both of you guys are extremely busy. If you dont have time to look I would understand completely. I'll keep tinkering until I figure it out.

For reference the flow logic behind my use case is:

- provide a source and destination directory as well as a directory for individual log files.
- process the source directory and create a robocommand job for each subdirectory 
- create a robocommand job for the root of source directory but not subdirectories
- proceed with the copy in parallel (max of 8 at a time)
- completed. 
- Can compare source and destination anytime to confirm that at lease the structure and file listing matches.

just let me know, thanks.

**Comment by RFBomb** [comment]
Looks like something with the underlying list’s implementation of INotidyCollectionChanged

**Comment by justind-dev** [comment]
Thats what I was thinking. I chalked it up to the possibility I wasnt using RoboQueue in the way it was designed possibly but wanted to make sure.

**Comment by justind-dev** [comment]
Noticed the new commit modifying the INotifyCollectionChanged, pulled and ran a test again but have another error on what looks to be the same interface. 

Details:

```
System.ArgumentException
  HResult=0x80070057
  Message=Reset action must be initialized with no changed items. (Parameter 'action')
  Source=System.ObjectModel
  StackTrace:
   at System.Collections.Specialized.NotifyCollectionChangedEventArgs..ctor(NotifyCollectionChangedAction action, IList changedItems, Int32 startingIndex)
   at System.Collections.Specialized.NotifyCollectionChangedEventArgs..ctor(NotifyCollectionChangedAction action, IList changedItems)
   at System.Collections.Generic.ObservableList`1.Clear() in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\RoboSharp\GenericListWithEvents.cs:line 154
   at RoboSharp.RoboQueue.StartAll(String domain, String username, String password) in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\RoboSharp\RoboQueue.cs:line 414
   at RoboMigratorGUI.Form1.<StartMigration>d__10.MoveNext() in C:\Users\20830516x\Development\CSHARP\RoboMigrator\RoboMigratorGUI\Form1.cs:line 158
```

**Comment by justind-dev** [comment]
Linking this https://stackoverflow.com/questions/4588359/implementing-collectionchanged in case it provides any clues. I dont know enough to know how relevant it is. Again can't rule out I am using it maybe in a way that is outside scope I guess.

**Comment by justind-dev** [comment]
So commit 5a8eac0 which changes the NotifyCollectionChanged actions fixed the above issue but now ran into another one immediately after.

https://i.imgur.com/Nq47JSS.png
Above screenshot shows where the error happens and the data for the ProcessedFileInfo. Seems like this doesnt look right. It correctly copied one directory but then throws this.

Seems like the data / file name fields are not properly populated possibly? 

*Also, if I should  not be replying to this thread, please let me know!

**Comment by RFBomb** [comment]
First, appreciate the testing, its needed. 
I could've used an observablecollection and made this a whole lot easier on myself, but I liked the additional functionality that List provdies over it.
Fixed.

**Comment by justind-dev** [comment]
You are the bomb! That fixed it. I can not supply a direcotry and it will automatically create individual jobs for the directories below it. Looks like my logic somehow has it running synchronously waiting for each last task to finish but I can figure that out probably. Appreciate all you guys do on this neat little wrapper / library. Maybe one day I will be able to contribute. 

Thanks again.

**Comment by RFBomb** [comment]
By default, it runs 1 at a time. Update MaxConcurrentJobs to run multiple at a time. Set 0 for all at once.

**Comment by RFBomb** [comment]
#138  Merged in, this can be closed. Please use /Dev branch.
