### ISSUE TITLE
Event Handler Not Firing OnCopyProgressChanged

### ISSUE THREAD

**Issue by solemnpaladin** [tjscience/RoboSharp#13]
Hi, 

First, I want to say that I am really liking this library and it has already saved me ton of time and effort on a current project!  With that said, I believe that I have run into and issue with the OnCopyProgressChanged event handler not firing properly. I have set a breakpoint in the event handler and it never fires. I have included snippets of the logic I am using just encase I am doing something bone-headed.

My Button Click Event:
```
public FormMain()
{
      InitializeComponent();

}

private static Logger logger;
RoboCommand roboCMD = new RoboCommand();

// Lots of code in between :-)

private void buttonFMMigrate_Click(object sender, EventArgs e)
 {
        buttonFMMigrate.Enabled = false;
        buttonMigrationToggle.Visible = true;
        buttonStopMigration.Visible = true;

        MigrateFiles();

        buttonFMMigrate.Enabled = true;            
        buttonMigrationToggle.Visible = false;
        buttonStopMigration.Visible = false;    
           
 }
```

MigrateFiles() Starts things up:

```
public void MigrateFiles()  
 {
         // Set Event Handlers
         roboCMD.OnCopyProgressChanged += roboCMD_OnCopyProgressChanged;
         roboCMD.OnFileProcessed += roboCMD_OnFileProcessed;
         roboCMD.OnCommandCompleted += roboCMD_OnCommandCompleted;

         // Set Copy Options
         roboCMD.CopyOptions.Source = textBoxFMDisplaySourcePath.Text;
         roboCMD.CopyOptions.Destination = textBoxFMDisplayDestinationPath.Text;
         roboCMD.CopyOptions.UseUnbufferedIo = true;

         if (checkBoxFMCopySubDir.Checked)
         {
             roboCMD.CopyOptions.CopySubdirectories = true;
         }

         else if (checkBoxFMCopySubEmpty.Checked)
         {
             roboCMD.CopyOptions.CopySubdirectoriesIncludingEmpty = true;
          }
          logger.Info(textBoxFMFileCount.Text + " Files Found");
          logger.Info("Starting Migration...");

           roboCMD.Start();

 }

```
And finally the "On_CopyProgressChanged" Event Handler:

```
private void roboCMD_OnCopyProgressChanged(object sender, CopyProgressEventArgs e)
{
           progressBarFM.Invoke((MethodInvoker)delegate
           {
               progressBarFM.Value = (int)e.CurrentFileProgress;
           });

           labelFMPercentage.Invoke((MethodInvoker)delegate
           {
               labelFMPercentage.Text = string.Format("{0}", e.CurrentFileProgress.ToString());
           });
}

```

**Comment by tjscience** [comment]
I just checked the sample app and the OnCopyProgressChanged event is being hit. Can you try to put a Console.WriteLine(e) at the very top of the callback method? Maybe, the code inside of the MethodInvoker is not being executed properly.

**Comment by solemnpaladin** [comment]
Thanks for the quick response! I added Console.WriteLine(e) to the top of the event and the break still does not trigger:

![image](https://cloud.githubusercontent.com/assets/13835005/16469052/f22a2c2e-3e1c-11e6-8244-15ecf7d8cc1e.png)

It appears that it doesn't get to the Console.Writeline(e) so I don't believe the delegate is the issue.  

I perused the code in the RoboCommand class in the library and noticed that you are determining progress if the line ends with "%".  Do I need to use a certain logging flag so that the "%" is present from the redirected output from robocopy?  I didn't use any logging flags and just used the copy subdirectories switch (/S).

 ```
if (data.EndsWith("%", StringComparison.Ordinal))
 {
          // copy progress data
           if (OnCopyProgressChanged != null)
           OnCopyProgressChanged(this, new CopyProgressEventArgs(Convert.ToDouble(data.Replace("%", ""))));
  }

```
Again, I really appreciate the quick response and you taking the time to look into this. :-)

**Comment by tjscience** [comment]
You should not have to change any of the logging options. In fact, the only setting that I know which will prevent the CopyProgress callback from occurring is setting RoboCommand.LoggingOptions.NoProgress = true. This will prevent the callback for the CopyProgressChanged handler. Are you setting this flag to true anywhere?

**Comment by solemnpaladin** [comment]
Sorry for my delayed response and thanks for your quick one,

What you say makes sense, it's just that if the "%" is missing in the output from RoboCopy the event will not fire based on the logic you are using to detect a change.

I have not explicitly set  `RoboCommand.LoggingOptions.NoProgress = true `. I will dig further and see what Robocopy output I am getting. If I cannot pinpoint the cause, would you be up for doing a private GoToMeeting so that I can give you a more in-depth look at what I am seeing?  

Thanks again for your time and attention with this :-)

**Comment by solemnpaladin** [comment]
Oops...Sorry I accidently closed the issue

**Comment by tjscience** [comment]
Can you try to run robocopy in powershell and see if it gives you the % symbol?

**Comment by solemnpaladin** [comment]
I just ran Robocopy in Poweshell with the same source and destination paths that I used to test my application with and the % are printing like they should. So it appears that parsing out the % is not the problem.

Instead of using the dll,  I will pull RoboSharp's classes directly into my application and attempt to trace out what is happening. I will let you know what I find. 

Thanks as always for your help :-)

**Comment by solemnpaladin** [comment]
Again sorry, about the long delay in response, my work schedule has been hectic. 

Anyway, I removed the reference to the dll and put all of the classes directly into my project and it worked without issue.  Originally I just usedthe NuGet plugin, could it be something with that version?

**Comment by tjscience** [comment]
The nuget package should consist of the latest code. I use appveyor to automate the build process. Can you try an older version of the nuget package and see if that works?

**Comment by tjscience** [comment]
Hi @solemnpaladin . I am going to close this due to inactivity. If you feel the need or have additional information, please don't hesitate to re-open it. Thanks!
