### ISSUE TITLE
Net40 Support

### ISSUE THREAD

**Issue by RFBomb** [tjscience/RoboSharp#136]
Formal request to drop Net40 from target frameworks. 

Net40 has been deprecated and has not received security updates since 2016. It also prevents use of Async methods, along with await.

it would also remove the need for the `#if net40` statements, since nearly all of the other targets (save for edge cases easily worked around) have support for nearly all the same methods available. 

My reason for this request is RoboQueue. During my testing, what I’ve been seeing is that occasionally RoboCommands get stuck in a ‘waiting to run’ state while the RoboQueue method is in its sleep loop, meaning it is at a standstill that will Never complete. Using `await Task.delay` Frees the thread up to do work, such as starting the robocopy start command. 

What I propose:
- take all the improvements from RoboQueue except the BackupApp changes and RoboQueue itself and submit them as PRs. This bring any changes I did to optimize /improve/ clarify them to all items. 
- Create a new fork that can continue Net40 support bug fixes if needed. 
- One last Nuget Package that includes Net40 support, put it into the readme. 
- Then remove it from dev

**Comment by PCAssistSoftware** [comment]
All of that makes perfect sense to me, and I fully agree, But let's see what @tjscience has to say on the matter first :)

**Comment by RFBomb** [comment]
That’s why I made it a new issue! 
(and just in case any Net40 projects around still exist that are using this have a reference thread to look at if they pull an incompatible release)

**Comment by RFBomb** [comment]
Net40 branch created.
