### ISSUE TITLE
Race condition on program exit, Task does not actually run

### ISSUE THREAD

**Issue by jrosenth** [tjscience/RoboSharp#15]
First, this is a great package, it saved me a bunch of time.  Thanks

I've found what seems to be a race condition where the ".Start()" method can be called however the program can exit before the underlying "Task" is actually executed.

I have a console application which creates big files and periodically copies them to network location.  As the program is finishing it attempts to copy the last file it created.  Start() is called, the "Task" is scheduled (queued) because that's what Task.Run does, but the program can exit before the "Task" actually gets executed by the scheduler.

It would be nice if the underlying "Task" was not private and accessible by the calling application.  If it was the application could wait and ensure it is actually executed before exiting.

Jay R.

**Comment by tjscience** [comment]
Hi Jay R. I am glad that you like the package and it has been useful! What you propose is certainly a good idea and I see no reason to not fulfill that request. It is also super easy, so let me throw that in. Thanks!
