### ISSUE TITLE
No Destintation

### ISSUE THREAD

**Issue by generik0** [tjscience/RoboSharp#16]
Hi 
I get a very strange issue when using the tool:

ROBOCOPY     ::     Robust File Copy for Windows
Started : 17. august 2016 21:42:14
Source : c:\tmp\Zatea\from" c:\tmp\Zatea\to"\
Dest -
Files : *.*
Options : *.* /BYTES /S /E /COPYALL /R:1 /W:2
ERROR : No Destination Directory Specified.
Simple Usage :: ROBOCOPY source destination /MIR
source :: Source Directory (drive:\path or \\server\share\path).
destination :: Destination Dir  (drive:\path or \\server\share\path).
/MIR :: Mirror a complete directory tree.
For more usage information run ROBOCOPY /?
****  /MIR can DELETE files as well as copy them !

using (var backup = _roboSharp.Create())
{
   backup.OnFileProcessed += Backup_OnFileProcessed;
   backup.OnCommandCompleted += Backup_OnCommandCompleted;
   backup.OnCommandError += Backup_OnCommandError;
    backup.CopyOptions.Source = configuration.PathFrom;
   backup.CopyOptions.Destination = configuration.PathTo;
   backup.CopyOptions.Mirror = false;
   backup.CopyOptions.CopySubdirectoriesIncludingEmpty = configuration.CopySubDirectories;
   backup.CopyOptions.CopyAll = true;
   backup.RetryOptions.RetryCount = 1;
   backup.RetryOptions.RetryWaitTime = 2;
   backup.Start();
}

How can this be wrong.
On win 10. .net 4.52

**Comment by tjscience** [comment]
Hello. Just looking at what you posted leaves me wondering what the backup.CopyOptions.Destination is being set to. Have you made sure that there is a valid value in configuration.PathTo?

**Comment by generik0** [comment]
It is very strange. I just cardcoded it and it works. But back to the variables and it failes.
Take a look at the picture:
![2016-08-17_22-24-13](https://cloud.githubusercontent.com/assets/2411563/17751884/7b8a0444-64c9-11e6-8f6c-248cd1a645ea.jpg)

**Comment by generik0** [comment]
Wait. it works now. It was just my configuration.
I had added a "\" so it became C:\\tmp\\Zatea\\to\\ not C:\\tmp\\Zatea\\to

**Comment by generik0** [comment]
BTW. Cool tool. Thanks"

**Comment by tjscience** [comment]
No problem! I am glad you like it.
