### ISSUE TITLE
Performance problems when files exist in the destination folder 

### ISSUE THREAD

**Issue by 19Zer0s** [tjscience/RoboSharp#166]
Hello,

I currently have the problem that I have massive performance problems when I use the option "LoggingOptions.OutputToRoboSharpAndLog = true" but **ONLY** if the files I want to copy already exist in the destination folder. 
The problem does **not** occur if I set the option LoggingOptions.OutputToRoboSharpAndLog to False. 

This is the duration (in green at the end) of the copy job when the files do **NOT** exist in the destination folder.
![CopyTime when Files DONT exsist in destination folder](https://user-images.githubusercontent.com/112169820/212495749-948633dd-b34b-4093-9bde-7d14c292046d.PNG)

This is the duration (in green at the end) of the copy job when the files **DO** exist in the destination folder.
![CopyTime when Files exsist in destination folder](https://user-images.githubusercontent.com/112169820/212495758-9420b02e-bae9-4dcf-8c56-0e8b181b939c.PNG)

Does anyone have an idea why this problem occurs?

**Comment by PCAssistSoftware** [comment]
What value (path) do you have set for your .LogPath? make sure you are not writing the log to a location (path) within either your destination or source paths - set it to somewhere completely different, away from your sources or destinations.  

I might be missing the point completely - just a thought.

**Comment by 19Zer0s** [comment]
Thank you very much, this has improved the performance considerably 
(But it is still slower if the files already exist in the destination folder is that normal?)

This is the duration (in green at the end) of the copy job when the files do NOT exist in the destination folder.
![image](https://user-images.githubusercontent.com/112169820/212498213-de19a394-51ab-4b2a-a8a1-ef1c7d86055e.png)

This is the duration (in green at the end) of the copy job when the files DO exist in the destination folder.
![image](https://user-images.githubusercontent.com/112169820/212498244-fe56853e-7902-4a2f-af26-f855ad0068af.png)

**Comment by PCAssistSoftware** [comment]
Yes I would expect it to be a bit slower as it has more work to do as it has to scan to see what files exist first

**Comment by 19Zer0s** [comment]
Okay, thanks, that really helped me a lot
