### ISSUE TITLE
The OnCopyProgressChanged Event does not get called. 

### ISSUE THREAD

**Issue by 19Zer0s** [tjscience/RoboSharp#169]
Hello,

I currently have the problem that the event OnCopyProgressChanged is not called neither by the RoboQueue nor by my RoboCommands. (idk if called is the right term for that but i hope u can understand what i mean)

Do i need to set some options on my RoboQueue or RoboCommands for that to work?
or does someone know how to fix that?

**Comment by PCAssistSoftware** [comment]
It definitely works as I use it in my own app which uses RoboSharp.

Make sure you are adding the handler for it e.g. the below if using VB.NET

 `AddHandler queue.OnCopyProgressChanged, AddressOf RoboCommand_OnCopyProgressChanged`
