### ISSUE TITLE
It don't starts

### ISSUE THREAD

**Issue by phenomarc** [tjscience/RoboSharp#17]
Hi, I'm writing a console application using robosharp.
I've wrote this method:
` static void robosharp(string sPath, string dPath)
        {
            RoboCommand copy;
            copy =new RoboCommand();
            copy.CopyOptions.Source = sPath;
            copy.CopyOptions.Destination = dPath;          
            copy.CopyOptions.CopySubdirectories = true;
            copy.CopyOptions.CopySubdirectoriesIncludingEmpty = true;
            copy.CopyOptions.CopyAll = true;
            Console.WriteLine("Starting backup process... This will take a while.");
            copy.Start();
            Console.ReadLine();
            Console.WriteLine("BACKUP COMPLETE");
        }`
And then I call it in Main using:
`robosharp(sourcePath, destinationPath);`
with 
`string sourcePath = "E:\\";        
 string destinationPath = "G:\folder";`
But when I execute the app, it don't copy anything.
What I'm doing wrong?

**Comment by tjscience** [comment]
Hi @phenomarc , 

This may not be the issue, but it looks like your path is not correct for the destination. You need to escape your backslash like so, 

> "G:\\folder"

If that does not work, try running in robocopy itself to see if it copies.

**Comment by phenomarc** [comment]
Thanks for the answer. I have this in my code (not in my comment), but now I change the folder name, and when I run the program, it creates the folder, but don't copy anything. I'm thinking maybe the issue in in my robosharp method.

**Comment by phenomarc** [comment]
Well, it seems that I fixed my issue, changing \\ to //. Now is copying great.
Many thanks for this awsome tool.
