### ISSUE TITLE
How to use the progressbar with robocopy

### ISSUE THREAD

**Issue by ilsanto2** [tjscience/RoboSharp#172]
Hi all, I'm using robocopy in c# and it works very well and is fast, but I haven't found how to use the progress bar while copying files.
In the examples you can see the filename and more..., but I haven't found a way to see the progress of copying files.
You can help me.
Thank you

**Comment by PCAssistSoftware** [comment]
You need to handle the "OnCopyProgressChanged" event and in here e.CurrentFileProgress has the Current File Progress Percentage which you can  use to show progress of current file in a progress bar, that's what I do in my app

**Comment by ilsanto2** [comment]
It works thanks, I was expecting total progress copying all files.
Instead the progression occurs for each copied file...

**Comment by PCAssistSoftware** [comment]
there are ways of doing that as well, I also do that in my apps.  Firstly run with the listonly switch set so that you can get statistics of how many files / dirs / bytes to copy, and then you can code in showing overall progress however you wish in your own code when running without the listonly switch and doing the actual file copy

**Comment by ilsanto2** [comment]
Perfetto

**Comment by ilsanto2** [comment]
I wanted to use StartAsync_List option to have a progress bar for copying a DIR, I tried setting this

`copyCommand.StartAsync_ListOnly(dir name);` 

`void CopyCommand_StartAsync_ListOnly(RoboSharp.Interfaces.IRoboCommand sender, CopyProgressEventArgs e)`
`{`
 `  this.Dispatcher.Invoke((Action)(() =>`
  ` {
   `progressBar.Value = e.CurrentFileProgress;`
    `}));`
`}`
How should I set it?
Thank you

**Comment by ilsanto2** [comment]
Resolved

**Comment by neo125874** [comment]
@PCAssistSoftware Hi, thanks for the robocopy. 
but we encounter an issue of listonly and copy, we first use listonly to add totalFiles+totalDirs in OnCommandCompleted, 
then use mirror copy to print progress in OnFileProcessed
`processedFiles++;
                copiedBytes += fileProcessedEvent.ProcessedFile.Size;`
and finally 
`double fileProgressPercentage = (double)processedFiles / (totalFiles+totalDirs)* 100;
            double byteProgressPercentage = (double)copiedBytes / totalBytes * 100;`
the byteProgressPercentage would meet 100%, but fileProgressPercentage  exceed 100%, 
any idea of us forgot to take into consideration?

**Comment by PCAssistSoftware** [comment]
why adding files and dirs? they are two totally different things and should be handled separately.  And if you are adding the ProcessedFile.Size when the .FileClass is a DIR then this value is not a size it is a count of how many files are in that directory.
