### ISSUE TITLE
Interrupted copying files

### ISSUE THREAD

**Issue by ilsanto2** [tjscience/RoboSharp#173]
How does the error event work if it loses its path and copying stops…
I managed the events

`copyCommand.RetryOptions.RetryCount = 2; 
 copyCommand.RetryOptions.RetryWaitTime = 5;`

and after several attempts it ends up going to the completed event
` void CopyCommand_OnCommandCompleted(RoboSharp.Interfaces.IRoboCommand sender, RoboCommandCompletedEventArgs e)
        {  } `

So I tried the error event
` copyCommand.OnError += CopyCommand_OnError; `
` void CopyCommand_OnError(IRoboCommand sender, RoboSharp.ErrorEventArgs e)
        { 
         .......
        }`
I expected that after failed attempts, it would enter the error event causing it to generate a message and not enter the completed event
I don't understand how the error event works...where am I wrong?

Thanks

**Comment by PCAssistSoftware** [comment]
I think the example GUI shows it working if I remember correctly - but in my app I just add handler to the OnError event, and in that event e.Error contains the file name and information on what error occurred, which I can then deal with accordingly

**Comment by PCAssistSoftware** [comment]
Closed due to inactivity / lack of response.  OP can reopen if further comment required
