### ISSUE TITLE
CopyOptions.MultiThreadedCopiesCount make Speed Slow

### ISSUE THREAD

**Issue by weng7654** [tjscience/RoboSharp#175]
The CopyOptions.MultiThreadedCopiesCount option slows down both the logging and file transfer. By default, this option is set Default 0 and doesn't utilize multiple threads for the operation. However, enabling this option can make the file copying process significantly slower than expected, and the progress display may also be delayed.

The official recommendation is to use the /MT option from the command line, along with redirecting the log output to a file using /LOG+xxxx. It is uncertain whether the decrease in speed when using C# compared to using the command line is due to C#'s intrinsic multi-threading capabilities.

If the file copying process is significantly faster when operating through the command line, it suggests that the performance difference may be related to the way the multi-threading is implemented in C#.
It don't know How to Solve this Problem

**Comment by PCAssistSoftware** [comment]
CopyOptions.MultiThreadedCopiesCount is not needed when using RoboSharp as all multitasking is handled within the code using System.Threading.Tasks and multiple jobs can be run using RoboQueue to improve performance.

**Comment by PCAssistSoftware** [comment]
Also you don't need to use /LOG with RoboSharp as it has its own built in logging which works really well

**Comment by weng7654** [comment]
In the official documentation that I have read, it says: "Creates multi-threaded copies with n threads. n must be an integer between 1 and 128. The default value for n is 8. For better performance, redirect your output using the /log option. The /mt parameter can't be used with the /ipg and /efsraw parameters."

I wanted to set a higher value for the number of threads, but I found that it resulted in slower speed. Even when I manually set it to the default value of 8, the final data processing was still much slower than expected. 
However, when I use the same command in CMD, I do not have this issue.
What could be causing this?

**Comment by PCAssistSoftware** [comment]
The official documentation refers to RoboCopy.  RoboSharp is a wrapper for RoboCopy so works in a different way so some of the switches are not valid when used with RoboSharp (as explained above) as the functionality is already handled internally in the code itself, /MT is one of those as multi-threading is handled by the C# coding within RoboSharp using System.Threading.Tasks, so it is advised not to change the value of /MT when using RoboSharp as it will causes problems.

**Comment by weng7654** [comment]
Finally, I found that it's not a speed issue, but a problem with the statistics. Later, I directly ran robocopy and redirected the output to a log file. After using /MT:n, I discovered that the structure of the log changed, which is the reason for the incorrect file statistics. This may be a problem with robocopy itself. I don't know if Microsoft has optimized it or not. After using the /MT parameter, the structure of the log output completely changed. I'm not sure if there are any plans to support this log structure in future projects.

**Comment by PCAssistSoftware** [comment]
If you change the MT value then it breaks the RoboSharp logging / statistics which is why I suggested not to change it.

RoboSharp has its own built in logging and statistics which has been worked on and tested extensively and works really well.  If you want to use the standard Robocopy logging then just use standard robocopy with /Log.  If you want the added functionality of queues, statistics and everything else that has been provided with robosharp then use this project.
