### ISSUE TITLE
[Question] Parse Robocopy Parameters

### ISSUE THREAD

**Issue by LordPinhead** [tjscience/RoboSharp#187]
Hi,

we use Robocopy for many server applications and we put our parameters for each service into an etcd vault to change the parameters if needed on the fly.
Now I found this little gem and love the idea of getting the feedback of Robocopy in our browser windows, but I don't want to tell my people to forget about the Robocopy parameters and learn new ones.

So how can I use the old rc options / settings and let them get parsed and used? Or is that not done atm, do I have to make a pull and make the parser myself?

**Comment by RFBomb** [comment]
Hello, we must've forgotten to check here with all the holiday hub-bub. 

This was a conundrum I had attempted to created a solution for @PCAssistSoftware, and what I landed on was two solutions:

JobFile - this class when used to save a command will save it as the RCJ file that robocopy likes to store option with. (We actually simply run the command as a save only to generate the file).  `JobFile.Parse` is how you can take that native rcj file and load it back into RoboSharp. 

I believe I have also implemented the feature of robocopy where you can import multiple rcj files. (For this, parse each one, then apply them together to Robocopy) 


---

The other solution is much more recent. This uses `RoboCommandXmlSerializer` to save a collection of commands to a single xml file, whereas the other serializer currently implemented created a new rcj file for each command. 

---

If your existing files are stored in RCJ format (as in saved by robocopy), JobFile.Parse should work. If it's in your own custom format, you would need to create a parser. But `RoboCommandFactory` was designed for this use case, as I use it to generate commands on the fly in my application.

**Comment by LordPinhead** [comment]
I added a class to parse the CMD parameters, so users can migrate to the library without changing their settings or call parameters.
Maybe it´s just for me, but I´ll make a pull request when I have time and add it. 

Thx for the Info nonetheless, it would be great when you would release the change into this main repo.

**Comment by RFBomb** [comment]
@LordPinhead  - Are you suggesting a method to create a RoboCommand by parsing the command prompt parameters? ( ex : ` robocopy "Source" "Destination" /XC /E ` )

**Comment by LordPinhead** [comment]
The last part, "/XC /E /A" etc.
It's a pretty easy parser, I have a lot on my table right now, but I started with the parameters our people use in the company jobs.

It's just a foreach and a switch-case with all the options - I need some time to code down the rest and I will make a pull request later.

**Comment by RFBomb** [comment]
@LordPinhead  -- I have come up with a draft pull request for you to review at your leisure.
 #188 

As written currently, it handles all of the boolean items, but does not handle the collections (such as a list of files wildcards).

**Comment by RFBomb** [comment]
This was a fun little side quest. I think the implementation will be working by Friday. It's pretty much complete as is, just need to validate the exclusion parsing and review my unit tests.

**Comment by RFBomb** [comment]
@LordPinhead  please see that PR #188 - you should be able to submit your commands into this and produce the functional result. Let us know

**Comment by PCAssistSoftware** [comment]
closed as completed in PR #188
