### ISSUE TITLE
Clarification re values shown in SpeedStatistic.BytesPerSec and SpeedStatistic.MegaBytesPerMin

### ISSUE THREAD

**Issue by PCAssistSoftware** [tjscience/RoboSharp#189]
@RFBomb 

Hi, just noticed a potential anomaly in the results shown in SpeedStatistic.BytesPerSec and SpeedStatistic.MegaBytesPerMin which I wanted to run by you.

If I run the same job both with RoboSharp and with RoboCopy then I get the results as below for speed:

**RoboCopy command line:**

![image](https://github.com/tjscience/RoboSharp/assets/10872799/ad289fcd-f9fb-4a8f-80b1-1b68319ae379)

1,009,223,875 Bytes/sec
57,748.254 MegaBytes/min

**RoboSharp:**

BytesPerSec: 807.379
MegaBytesPerMin: 46.198

So just wondering if the results in RoboSharp are not actually bytes per second and megabytes per minute.  but **mega**bytes per second      and kilobytes per minute. 

See logic below:

a)  **mega**bytes per second  as 807.379 x 1024 x 1024  would be  846,598,242   which is more comparable to the 1,009,223,875  that RoboCopy shows for same job than the 807.379 it is actually showing.                

and 

b) megabytes per minute is actually **kilobytes** per minute  as 46.198 x 1024  would be 47,306.752 which is more comparable to the 57,748.254 that RoboCopy shows for same job than the 46.198 it is actually showing

**Comment by PCAssistSoftware** [comment]
EDIT: corrected b from above

b) megabytes per minute is actually **gigabytes** per minute as 46.198 x 1024 would be 47,306.752 which is more comparable to the 57,748.254 that RoboCopy shows for same job than the 46.198 it is actually showing

**Comment by RFBomb** [comment]
If those numbers are correct, that's a huge slowdown being introduced by RoboSharp/the UI. 

I'd be curious to benchmark it with RoboSharp in a console app that has zero reporting until printing the speeds at the end.

**Comment by PCAssistSoftware** [comment]
Here  is another example which is a bit closer in results e.g. less slowdown

![image](https://github.com/tjscience/RoboSharp/assets/10872799/90777d50-3fd7-4331-a41a-60b729a542c0)

But the point I was making is nothing to do with slowdown it is the units being incorrect...?  
 
But clearly bytes /sec (SpeedStatistic.BytesPerSec) is NOT Bytes in RoboSharp it is actually MegaBytes  - e.g. 624,041,595 / 1024 / 1024 = 595.132  (more like the 624.815 shown in RoboSharp)

and mb / min (SpeedStatistics.MegaBytesPerMin) is NOT MegaBytes in RoboSharp it is actually GigaBytes - 35,707.945 / 1024 = 34.871 (more like the 35.752 shown in RoboSharp)

**Comment by RFBomb** [comment]
Yea I wanted to jot my thought down while I had it while investigating the code itself.

I found the issue: The Parse method is converting each `,` to a `.`, then converting to decimal. This has the same effect of only taking the two left-most blocks.

`Replace(',', '.')`
Should be:
`Replace(',', '')`

**Comment by PCAssistSoftware** [comment]
Thanks Robert, I did take a look but missed that - I thought it must be a conversion issue somewhere :)

Re the speed difference, definitely a slowdown in my GUI at least compared to command line - will be interesting to do as you say and test in just a console app to see if same.

Can you do a PR to fix the parse method and I will get it merged?

Thanks again, thought I was going mad initially with the figures.

**Comment by RFBomb** [comment]
~~Can do tomorrow, that's an easy one. ~~
Took about a minute, all set #190

**Comment by PCAssistSoftware** [comment]
Thanks Robert, much appreciated

**Comment by PCAssistSoftware** [comment]
Hi Robert, now testing but still not getting results I expect to see for BytesPerSec

Test run using RoboCopy command line gives me speed stats of:

 Speed :           538,252,733 Bytes/sec.
 Speed :            30,799.068 MegaBytes/min.

RoboSharp is giving me:

BytesPerSec: 515348
MegaBytesPerMin: 29488

So still looks like BytesPerSec is actually being returned as MegaBytesPerSec as 515348 x 1024 = 527,716,352 which is more comparable to the result from RoboCopy command line

**Comment by PCAssistSoftware** [comment]
~EDIT: hold fire on previous response, may be my app confusing things now as look fine in demo "Backup App"~

**Comment by PCAssistSoftware** [comment]
EDIT2: confirmed same issue with demo "Backup App", so NOT my app causing the problem or changing the values

**Comment by PCAssistSoftware** [comment]
@RFBomb - after doing some testing I believe it may be the RegEx pattern on line 129 of SpeedStatistic.cs which is causing the problem here.  I have outputted the values of line1 and line2 BEFORE it is matched using RegEx and they show correctly.

e.g.

line1 and line2 show:

 Speed :           515,348,361 Bytes/sec.
 Speed :            29,488.471 MegaBytes/min.

But after regex pattern match they end up as:

515348
29488

so looks like the first value is getting trimmed before the last comma?

**Comment by RFBomb** [comment]
The regex was a hare wrong

**Comment by PCAssistSoftware** [comment]
Absolute star, thank you

One query, I noticed whilst looking through code - in speedstatistic.cs on line 70 onwards OnPropertyChange is showing OnPropertyChange("MegaBytesPerMin") for both BytesPerSec and MegaBytesPerMin.  Not sure what effect it has but shouldn't first one be OnPropertyChange("BytesPerSec ")

![image](https://github.com/tjscience/RoboSharp/assets/10872799/dab97835-4086-4bde-b470-8fe556f82dac)

**Comment by RFBomb** [comment]
good catch

**Comment by PCAssistSoftware** [comment]
All working perfectly for me, if you are happy then I will merge #190 and #191 now

**Comment by PCAssistSoftware** [comment]
Closed as fixed in #190

**Comment by DiegoPlanchenstainerAtBMGroup** [comment]
Hi @PCAssistSoftware @RFBomb ,

first of all thanks for this awsome project! I'm currently facing an issue which may be correlated to this topic.

I'm integrating RoboSharp in my application, I managed to set all the options to perform the copy in the way I want and it works.

Unfortunately, the program throws an unhandled exception when trying to parse the speed data in
ResultsBuilder.cs (line 100): `res.SpeedStatistic = SpeedStatistic.Parse(statisticLines[4], statisticLines[5]);`

I got:
```
statisticLines[4] = " Velocità:           257.555.063 Byte/sec."
statisticLines[5] = " Velocità:             14737,419 MB/min."
```

The regex match.Value for statisticLines[4] evaluates to "257.555.063" and thus the program throws an exception when trying to parse that value to decimal.

Have I missed some configurations or do you find this problem too?

Thanks

**Comment by RFBomb** [comment]
This is a parsing error due to CurrentCulture settings on the .Parse() call I believe. It looks like the regex pulled the value out fine, but the issue was the parsing.

What I'd recommend is see if you can resolve the issue and submit a PR. 

Specifically, i believe it is due to the current culture swapping . And , for thousands/decimals

**Comment by RFBomb** [comment]
@DiegoPlanchenstainerAtBMGroup I was able to verify this issue using your provided strings. Based on the cursory research I had time to perform today, it looks like Parse() may in fact by use the CurrentCulture.NumberFormatInfo when parsing. And there is no good way to pass this in for modification, especially in a scenario where the calling app may be different than the system's culture (system default uses `,` and app prefers `.`)

The parse method will have to be modified to accommodate both scenarios.

**Comment by RFBomb** [comment]
@DiegoPlanchenstainerAtBMGroup Resolves in #200

**Comment by PCAssistSoftware** [comment]
@RFBomb - excellent work on this, I have tested the PR and all works fine.  Happy to merge it tomorrow.

**Comment by RFBomb** [comment]
Go ahead, all set with it

**Comment by DiegoPlanchenstainerAtBMGroup** [comment]
Thank you very much for your fast fix, works like a charm!
