### ISSUE TITLE
Wording query

### ISSUE THREAD

**Issue by PCAssistSoftware** [tjscience/RoboSharp#194]
@RFBomb 

Quick query re something I noticed:

In https://github.com/tjscience/RoboSharp/blob/dev/RoboSharp/SelectionOptions.cs

For ExcludeFiles (/XF) it says "/// JobOptions file saves these into the /IF (Include Files) section" surely this should actually be "/XF (Exclude files)"  as unless I am missing something you don't want files you choose to exclude added to an **include** list?

https://github.com/tjscience/RoboSharp/blob/c0a2cd3e57c56bd2a4233fb70a0d77ee411dddb8/RoboSharp/SelectionOptions.cs#L210

For ExcludeDirectories (/XD) it says "/// JobOptions file saves these into the /IF (Include Files) section" surely this should be a) /XD and b) should say Directories not Files - as same as above surely you don't want directories you choose to exclude added to an **include** list?

https://github.com/tjscience/RoboSharp/blob/c0a2cd3e57c56bd2a4233fb70a0d77ee411dddb8/RoboSharp/SelectionOptions.cs#L248

**Comment by RFBomb** [comment]
Copy pasted the documentation notes when i wrote it, so the implementation should be correct but tooltip/notes are wrong

**Comment by PCAssistSoftware** [comment]
corrected wording - implementation is fine
