### ISSUE TITLE
Add "include modified" selection option

### ISSUE THREAD

**Issue by kiwiwings** [tjscience/RoboSharp#197]
Please provide the "include modified" (/im) option in the selection options.

I've adapted the included tweaked options, but I haven't got a test case yet, so it's not something to provide as patch.

**Comment by PCAssistSoftware** [comment]
I will take a look at adding this

**Comment by PCAssistSoftware** [comment]
**Notes**

The functionality of the /IM switch can be tested as follows:-

1) Have a source and destination folder containing the same file
2) Use [BulkFileChanger](https://www.nirsoft.net/utils/bulk_file_changer.html) (or similar) to change the created time of the source file
3) Running Robocopy without /IM switch will find nothing to copy, but running it with /IM switch will find the one file with different created time to copy

**Comment by PCAssistSoftware** [comment]
Implemented as requested in #198

**Comment by PCAssistSoftware** [comment]
> **Notes**
> 
> The functionality of the /IM switch can be tested as follows:-
> 
> 1. Have a source and destination folder containing the same file
> 2. Use [BulkFileChanger](https://www.nirsoft.net/utils/bulk_file_changer.html) (or similar) to change the created time of the source file
> 3. Running Robocopy without /IM switch will find nothing to copy, but running it with /IM switch will find the one file with different created time to copy

I will add to this that it also seems to be related to the archive bit being set or not.  The Microsoft documentation and the documentation on page below seem to vary on the description for the switch, and in testing I found that just changing the time as above wasn't always working, but if I cleared the archive bit it was.

https://ss64.com/nt/robocopy.html
