### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by PCAssistSoftware** [tjscience/RoboSharp#201]
@RFBomb 

More of a question than a issue, but can anything be done do you think to improve memory usage of RoboSharp?

Running a large job last night and even just the analyze /L process ended up using 8GB of memory according to Task Manager!

Screenshots below show a job I am currently running, not such high usage as last night just yet, but it has a long way to go so I suspect will end up the same.

![image](https://github.com/tjscience/RoboSharp/assets/10872799/e981137f-f7f8-4e7d-81a2-66db3f0de052)

Thankfully I have a good spec system so lots of RAM to play with, but have had issues on other computers with "Exception of type 'System.OutOfMemoryException' was thrown."

Have done some diagnostics whilst running it inside Visual Studio to try and determine where the memory is being used and it appears to be the ResultsBuilder - another screenshot below after digging down into Diagnostic Tools > Memory Usage> and using snapshots to compare app idle and app after running a job for 45 minutes.

![image](https://github.com/tjscience/RoboSharp/assets/10872799/83c66b91-d089-4c13-ad6a-7e32c5746bbe)

**Comment by RFBomb** [comment]
So this is something's I've been pondering myself, as there's been a lot of changes to the library and one thing that hasn't been taken into consideration is the memory impact, though I've been trying to be careful with my functionality changes on that front.

The results builder itself I believe was mostly untouched, other than integrating ProgressEstimator.

If you run that same command and write the results to a txt file, what is the size of the file?

**Comment by RFBomb** [comment]
For clarity, what I'm getting at is that the ResultsBuilder consists only of that string collection and ProgressEstimator. PE only stores calculated values, and a few strings (processedFileInfo objects).

The only thing I can think of regarding 'optimization' of that List<string> is:

- Create an option to not store the results at all (react to the line being written by robocopy, but don't store the string itself. (ResultsBuilderOptions)

- My second idea is an event or ILogger<string>, but RoboCommand already has an event when a file is processed, which is basically the same as the log line. So this would just add complexity where an already-existing event exists.

**Comment by PCAssistSoftware** [comment]
Hi, thanks for prompt response, now running the same command using RoboCopy to a txt file - will report back with size later.

It is a difficult area, as wouldn't want to lose functionality or do anything that changes how well it works, and certainly don't want to add complexity to it.   Especially anything that would affect ability to show progress which is a key feature I use.

One thought I had was (and not sure if this is possible as depends on how it is used and what affect it might have on functionality), but RoboCopyResults stores the whole log as LogLines, and I suspect this is the largest piece of information it holds?  And certainly from my instance last night the log created was over 1 million lines long.....  So could an option be not to store this value or is that information instrumental in how it calculates information for progress?

Also noticed last night and need to yet do more testing that even after my analysis (StartAll_ListOnly) was complete the memory wasn't freed up, not sure if it would then be freed when I started (StartAll), or if it was just because of above and the loglines it stored still using the memory up.  But perhaps it could be cleared one it had extracted all useful information out of it for the copy state.    Just thoughts from top of my head, may not even be relevant / possible and I am saying this from a usage point of view rather than looking through the code to see what can be done.

**Comment by RFBomb** [comment]
It should free the memory up when the command is disposed, or when the command is started again. But if the consuming app contains a reference to the list (or results builder) that memory won't be freed. This is something we can look at.

As for ResultsBuilder, the only thing it really cares about is the summary tag so it can parse out the summary values. The only other thing it does is store the log lines. It would be easy to create a new Options object for library-specific options, such as not retaining the log lines in working memory - process the line on the fly and discard it instead of adding to the list). 

Matter of fact, we have an options object already, the configuration object. A property "RecordLogLines" could be added to disable/enable the functionality.

**Comment by RFBomb** [comment]
Matter of fact, to make integration easier, I'd add a Configuration property to RoboCommandFactory to work with scenarios like this. This is why I created the factory in the first place, so that app-wide settings could be applied when creating the commands.

**Comment by PCAssistSoftware** [comment]
Sounds like some good ideas to me.  My command is still running to write to a txt file, but is already up to 1.31Gb in size, so fits with the logic that it is the loglines that are potentially consuming the most memory.

**Comment by PCAssistSoftware** [comment]
Results to text file just complete - 11,319,351 lines of information, a total of around 1.4Gb in size

**Comment by RFBomb** [comment]
Yea I'd hazard a guess that storing that in memory would take up more room as each is an object that needs to be tracked, and writing to file might have some optimizations for repeated strings that don't exist raw memory. I'll whip up some changes today, I thought of a good way to do it I think.

**Comment by RFBomb** [comment]
See #202
