### ISSUE TITLE
parser query

### ISSUE THREAD

**Issue by PCAssistSoftware** [tjscience/RoboSharp#206]
@RFBomb 

Hi 

Any idea why the first one below can be parsed correctly, but the second one gives "'Source and Destination were unable to be parsed.'" error?

```
Dim a = RoboCommandParser.Parse("\\pc-01\c$\Software C:\test ""."" /E /ZB /MIR")

Dim b = RoboCommandParser.Parse("\\servername\share D:\ ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH")
```

**Comment by RFBomb** [comment]
Likely the `$` if I had to guess. All the unc paths I was testing with had a $ to denote where the root folder started (which I believe is the standard for unc pathing?), and the second statement does not have a `$` in the source. 

I'd have to really look into it a bit more to verify this suspicion, but that's my first guess.

**Comment by PCAssistSoftware** [comment]
Thanks for replying.  As far as I am aware no you don't have to have a $ in a UNC path, you would only use a $ if accessing a hidden share such as C$ or ADMIN$ or IPC$. The dollar just indicates a hidden share.  Any other share you set up on a network would just be accessed using the name or IP address of the computer and the name of the shared folder e.g. \\servername\sharename  or \\192.168.1.2\myfolder

**Comment by RFBomb** [comment]
I was unaware of that nuance, as every share at my company uses $

Alright, so the regex needs to be modified to accommodate this then. 

Is it safe to assume shares/unc paths always start with `//` or `\\`? If so, the regex can likely be broken into share and local validators. 

Alternatively we open it up to be less discriminatory  `[:$]` ~> `[:$\\/]`, but that will allow the following the be treated as valid "my\example" (whereas previous that is not a treated as valid path as it does not contain : or $ )

**Comment by PCAssistSoftware** [comment]
Sorry for delay in replying.

Yes it is safe to assume UNC paths / shares will always start with \\\ or // e.g.

//servername/path   - Unix

\\\servername\path   - DOS/Windows

Personally I think first suggestion above is the best way to go rather than opening it up to be less discriminatory.

**Comment by PCAssistSoftware** [comment]
Meant to say any testing I can do to help resolve this please let me know.  I am not very good at RegEx so will rely on your skills for this if possible :)

**Comment by RFBomb** [comment]
I can likely rake a peek into this tomorrow, just create a collection of paths that should be considered valid, and a collection that are invalid. And I'll incorporate those examples into the unit tests. 

As far as regex, I use Regex101 to validate everything

**Comment by PCAssistSoftware** [comment]
Excellent, thank you, much appreciated

**Comment by RFBomb** [comment]
Some examples:

Allowed (with and without quotes, with and without trailing slash)
C:\
C:\SomeDirectory
//Server/Drive$/Folder
//Server/Folder


Disallowed:
Folder
Some/Folder
/Folder (though this is technically valid on Linux, but that's not standard use case so it's outside scope of this.)

That cover the base?

**Comment by PCAssistSoftware** [comment]
For Allowed the slashes would need to be other way round - as // would be for Linux / Unix

e.g. 

\\\Server\Drive$\Folder
\\\Server\Folder

But yes that covers the base

**Comment by RFBomb** [comment]
I was going to treat them as equivalent, as one is the `Path.AlternateDirectorySeperator`

**Comment by PCAssistSoftware** [comment]
@RFBomb - thank you so much for looking at this.

The following example doesn't seem to work

`  Dim x = RoboCommandParser.TryParse("C:\Users\darren\OneDrive\Desktop\Working \\XPSDESKTOP\test ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH", t)`

Source is fine, but destination is found as \\\XPSDESKTOP\t      rather than \\\XPSDESKTOP\test

EDIT: fixed GitHub formatting which had removed \ and * from pasted example

**Comment by RFBomb** [comment]
I had also wanted to update the logic to not create new strings every time it checks for a flag, so I used string builder instead here to accomplish it. 

As for that example, `/XPSDesktop` is Linux path formatting, I'm surprised it picked up anything for the destination. `//XPSDESKTOP/test` should work, as the regex is specifically looking for `//`

~~Also, your file filter shows as `"".""`, which doesn't go anything? Should it be `"*.*"` ?~~ it's early. File filter is `.`

**Comment by PCAssistSoftware** [comment]
Seems to be a GitHub formatting issue as I pasted it from Visual Studio and for some reason it changed it....  pasted again below as code snippet which displays correctly

\\\XPSDESKTOP\test - is the correct format for a **Windows** UNC path, if it was linux it would be // rather than \\\ - reference = https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths

> //XPSDESKTOP/test should work, as the regex is specifically looking for //

EDIT: and for info that doesn't work either - still get destination of //XPSDESKTOP/t rather than /test

`Dim x = RoboCommandParser.TryParse("C:\Users\darren\OneDrive\Desktop\Working \\XPSDESKTOP\test ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH", t)`

**Comment by PCAssistSoftware** [comment]
Just in case it helps resolve it, if I reverse the source and destination e.g.

` Dim x = RoboCommandParser.TryParse("\\XPSDESKTOP\test C:\Users\darre\OneDrive\Desktop\Working ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH", t)`

Then they parse correctly

**Comment by PCAssistSoftware** [comment]
Been "trying" to resolve this myself and I believe it maybe to do with the regex on line 42 of RoboCommandParserFunctions.cs, because when testing in Regex101 I get the same problem where it is only matching one character after the computer name in the UNC path, see screenshots below:

 
![image](https://github.com/tjscience/RoboSharp/assets/10872799/45212ba1-e420-4cdd-a11f-f0e22edfe24b)

**Comment by PCAssistSoftware** [comment]
Further information from my testing:

It parses correctly if a destination UNC path is quoted, so below works fine, which would indicate second regex on line 42 is working correctly

```
 Dim x = RoboCommandParser.TryParse("C:\Users\darre\OneDrive\Desktop\Working ""\\XPSDESKTOP\test"" ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH", t)

 Dim x = RoboCommandParser.TryParse("C:\Users\darre\OneDrive\Desktop\Working ""\\SERVER\c$\test"" ""*.*"" /COPY:DAT /DCOPY:DA /E /SEC /MOVE /R:2 /W:2 /V /FP /BYTES /NJH", t)
```

**Comment by PCAssistSoftware** [comment]
Now I am definitely no expert on RegEx, but playing with Regex101 changing line 42 from

`internal const string uncRegex = @"([\\\/]{2}[^*:?""<>|$\s]+?[$]?[\\\/][^*:?""<>|\s]+?) | (""[\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|]+?"")";`

to

` internal const string uncRegex = @"([\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|\s]*) | (""[\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|]+?"")";`

seems to work, but not sure of any other implications, so definitely need your input on it as I don't understand why it works or really what the changes I made have done....

**Comment by PCAssistSoftware** [comment]
@RFBomb - thank you very much for the last commits, initial testing appears that all is working well.  Is there anything specific changed I need to know about or test for in these changes?

Not sure if any of my previous replies were any use to you or not?  

Do we need to worry about the "All checks have failed - AppVeyor build failed" message or is that an expected issue now.

**Comment by RFBomb** [comment]
The examples were useful, as I was iterating the code I used them to create some other unit tests. 

The tests failing at the moment will be fixed, just hadn't gotten to it yet. I changed how the source/dest directory path was cleansed when setting it in copy options, and a few other tweaks for minor optimizations/robustness improvements. So there's still things I am going to be looking at, including why some tests hang or fail currently.

I suspect some of the failing tests are due to string literal comparisons with quoted/unquoted paths, but again I'll have to investigate. Currently at a trade show so time to work on this is sparse.

**Comment by PCAssistSoftware** [comment]
Excellent, thank you, I will continue testing today and report back later.

**Comment by RFBomb** [comment]
> `internal const string uncRegex = @"([\\\/]{2}[^*:?""<>|$\s]+?[$]?[\\\/][^*:?""<>|\s]+?) | (""[\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|]+?"")";`
> 
> 
> 
> to
> 
> 
> 
> ` internal const string uncRegex = @"([\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|\s]*) | (""[\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|]+?"")";`
> 


Cursory glance, you changed `[pattern]+?` to `[pattern]*` at end of first group. I changed mine to `([pattern]+)?` which is effectively same thing (from "match as many characters as possible, not greedy, but must be at least one" to "as many as possible, but may not exist"

To break it down:
Greedy definition `+`: Continue matching as much as possible. 

Not Greedy `+?` : if another subsection matches, this one ends, but this one will continue until that occurs or next character no longer matches this pattern. May lose last character in some instances. 

Pattern 1 - no quotes
> ([\\\/]{2}[^*:?""<>|$]+?[$]?[\\\/][^*:?""<>|\s]*)
- `[\\\/]{2}` Must start with directory separation, count of 2. 
- `[^*:?""<>|$]+?` match characters that are NOT in this group, must be atleast 1, but not greedy. Minimum 1 match. 
- `[$]?` optional $ character
- `[\\\/]` single directory separator that must exist
- `[^*:?""<>|\s]*` match anything NOT in disallowed characters collection, as many times as possible (greedy). Stops when reaches a disallowed character. Minimum 0 matches.  
- `)` end of this pattern. 

`|` OR attempt to match next pattern which is for quoted paths.

**Comment by PCAssistSoftware** [comment]
Thank you for the explanation of the RegEx - really useful to understand it more :)

**Comment by PCAssistSoftware** [comment]
After running multiple tests I can confirm this definitely resolves my initial problem - so thank you.

Below I will list any related problems I have found during testing:

**1**

Not sure this is something we can account for as it would really be down to user providing a really badly typed command, but if you parse something like below examples ( which have multiple slashes between computer name and path) then it gets confused and uses part of the malformed destination path as the file filter. 

I only found this after making a typo when testing commands and is so incorrect it would really be a users error, and I know we can't cover every eventuality, but mentioning it anyway for info.

```
c:\source \\servername\c$ /E /R:15
c:\source \\xpsdsktop\folder /E /R:15
```

**Comment by RFBomb** [comment]
So while technically the regex can accommodate those invalid inputs and cleansing them would likely be pretty trivial, my goal was to only cleanse and handle standard and proper inputs. Otherwise the possibilities are endless.

**Comment by PCAssistSoftware** [comment]
> So while technically the regex can accommodate those invalid inputs and cleansing them would likely be pretty trivial, my goal was to only cleanse and handle standard and proper inputs. Otherwise the possibilities are endless.

That makes perfect sense and is exactly what I thought you would say, but just mentioning things as I find them.

**Comment by PCAssistSoftware** [comment]
**2**

Bearing in mind I totally agree with your previous response, but is there at least a simple way of just ensuring that a user doesn't try and parse a string which is completely invalid, because using TryParse you can pass something like the below (e.g. complete gobbledygook and it comes back as True!

```
 Dim t As RoboCommand = Nothing
 Dim x = RoboCommandParser.TryParse("gfgfgfgfdgfdge4t434rty436464646", t)
```

**Comment by PCAssistSoftware** [comment]
Okay I have spent several hours today fully testing parsing across all my usage cases and it is now working fine for all UNC path variations I have tried, so thanks again for looking at this, much appreciated.

**Comment by RFBomb** [comment]
Good feedback on the TryParse. 

The reason this was successful is because current iteration ignores if both source and destination were not found, and only errors if one is found and other is not. 

This can be modified to require source/destination arguments for TryParse, and ignore them (as currently does) for ParseOptions

**Comment by PCAssistSoftware** [comment]
@RFBomb - Hi Robert, hope you are well.  When you have a few spare moments (I know you are busy), could you do whatever is required to #207 to allow me to merge it in if possible?  Anything I can do to help just let me know, I have already extensively tested it and all seems okay so far.

**Comment by RFBomb** [comment]
I think it's mostly complete. But these changes were mostly thrown together, and I'm going to give them a polish/review of my own before I say go ahead. 

I've been at a trade show for a few weeks, so haven't had much time to dedicate to any projects.

**Comment by PCAssistSoftware** [comment]
That's fine, I appreciate you looking at it and resolving the problem for me :)

**Comment by RFBomb** [comment]
Just an update to this, I have been chipping away at it and have several commits ready to push. But just had other tasks being put in front. Working out the last kinks to the unit tests. 


Some food for thought here:

- The default file filter '*.*' is actually unnecessary. Omitting it vs specifying it has no change to functionality to robocopy. I'm inclined to update it to not provide the argument by default, as it will make some of the unit testing easier (instead of adding an argument that wasn't in original parsed string). The FileFilters property will just default to an empty collection. 

- after some additional testing, I'm updating comments on the exclusion filters. Wild cards are allowed for basic filters ( *.pdf ) but not qualified filters ( C:/folder/my.pdf ). So you can specify exact folder/filenames to exclude, but those must not have wildcards.  I'm adding a method to add a file/directory exclusion to the respective lists, and was contemplating putting basic checks in place to guard against it. `if (fully qualified path) then check for wildcard. Error if present.` this will allow the library to throw exceptions upon receiving bad arguments for Exclusions if users submit them via the method. (Otherwise it will result in an event being raised when robocopy fails). 

- alternatively/in addition to the above change, that sanity check could be done during startup, and throw an exception prior to issuing the command to robocopy (which will the. Just error out due to invalid parameter). 


Thoughts ?

**Comment by PCAssistSoftware** [comment]
> * The default file filter '_._' is actually unnecessary. Omitting it vs specifying it has no change to functionality to robocopy. I'm inclined to update it to not provide the argument by default, as it will make some of the unit testing easier (instead of adding an argument that wasn't in original parsed string). The FileFilters property will just default to an empty collection.

That makes perfect sense to me

> * after some additional testing, I'm updating comments on the exclusion filters. Wild cards are allowed for basic filters ( *.pdf ) but not qualified filters ( C:/folder/my.pdf ). So you can specify exact folder/filenames to exclude, but those must not have wildcards.  I'm adding a method to add a file/directory exclusion to the respective lists, and was contemplating putting basic checks in place to guard against it. `if (fully qualified path) then check for wildcard. Error if present.` this will allow the library to throw exceptions upon receiving bad arguments for Exclusions if users submit them via the method. (Otherwise it will result in an event being raised when robocopy fails).

> * alternatively/in addition to the above change, that sanity check could be done during startup, and throw an exception prior to issuing the command to robocopy (which will the. Just error out due to invalid parameter).

Totally agree with logic and throwing exception if fully qualified path contains a wildcard, think it would make more sense to be when adding the command to robocopy

**Comment by RFBomb** [comment]
> Totally agree with logic and throwing exception if fully qualified path contains a wildcard, think it would make more sense to be when adding the command to robocopy

Alright, so the proposed change will validate the file filters (illegal characters only), `XF` and `XD` options, prior to submission into to the RoboCopy process. Should be fairly trivial to set up.

**Comment by RFBomb** [comment]
Alright, I'm leaving that wildcard validation for a future PR, as when I went to implement it I wasn't sure how I wanted to do it. So I left it for now. If someone needs that functionality in the future that thought can be revisited.

I have pushed several additional commits to the PR, and reviewed the unit tests and the code. I will be giving it a cursory glance tomorrow, and dropping the dll into my main app I work with, ensure nothing funny occurs there, then give the go-ahead.

**Comment by PCAssistSoftware** [comment]
> Alright, I'm leaving that wildcard validation for a future PR, as when I went to implement it I wasn't sure how I wanted to do it. So I left it for now. If someone needs that functionality in the future that thought can be revisited.

That's fair enough and understandable

> I have pushed several additional commits to the PR, and reviewed the unit tests and the code. I will be giving it a cursory glance tomorrow, and dropping the dll into my main app I work with, ensure nothing funny occurs there, then give the go-ahead.

I will also do similar tomorrow and do some testing and report back

**Comment by PCAssistSoftware** [comment]
Good morning, I have been doing some testing of the PR in some of my key apps which use RoboSharp and so far all my testing of parsing etc is working fine. 

If there are any specific areas you need testing relating to changes in this PR then please let me know.

So far the only comment I have is something we discussed above and that is trying to potentially handle if complete gobbledygook is passed to .TryParse (or even .Parse and .ParseOptions) to not come back as True.  I know this may come under user error and making sure you provide a correct string.

The examples below parse "okay / true" when content is completely invalid, and seem to assume what you have provided is a file filter

```
Dim t As RoboCommand = Nothing
Dim x = RoboCommandParser.TryParse("gfgfgfgfdgfdge4t434rty436464646", t)

Dim d = RoboCommandParser.ParseOptions("gfgfgfgfdgfdge4t434rty436464646")
Dim f = RoboCommandParser.Parse("gfgfgfgfdgfdge4t434rty436464646")
```

However not to worry if you deem this a user issue rather than a library issue.

**Comment by RFBomb** [comment]
So, that should just create a RoboCommand with a junk file filter. I think it's unrealistic to handle all scenarios, especially with known bad input. 

It did technically parse successfully, it just failed to find any worthwhile data. The only thing I can think of at the moment is that maybe `Parse` should error if either Source or Destination is missing (must have both). And that's easy to implement. But `ParseOptions` would still accept that string without issue. Thoughts on throwing if source/destination is empty?

**Comment by RFBomb** [comment]
Maybe having Parse throw if source/destination are empty is correct here, as the command isnt immediately runnable.

**Comment by PCAssistSoftware** [comment]
> Maybe having Parse throw if source/destination are empty is correct here, as the command isnt immediately runnable.

I completely agree with this idea.

Also just ran all the tests as well - results below:

![image](https://github.com/tjscience/RoboSharp/assets/10872799/f5317be6-0346-4b58-8242-e1dfad5dd52b)

**Comment by RFBomb** [comment]
Alright, when I get to work I'll re-run the tests (in VS2019 and VS2022) after adding in that error. It'll be like 2hrs

**Comment by RFBomb** [comment]
So, all unit tests were passing on my computer using VS2022, and I ran them multiple times. I can run them in VS2019 shortly.

**Comment by PCAssistSoftware** [comment]
Just run again here in VS2022 and for some reason still get those 5 failures - screenshot below shows error information if it helps

![image](https://github.com/tjscience/RoboSharp/assets/10872799/245346da-8ce7-4019-90f1-eab7b09c7fdb)

**Comment by RFBomb** [comment]
I have those same tests failing, investigating..

**Comment by RFBomb** [comment]
@PCAssistSoftware - I believe this was a change to robocopy functionality, which is why the unit test started failing! ( I could have sworn this passed previously)

The unit test does not request extras to be shown ( ReportExtras and Verbose are false). Yet Robocopy seems to always report them. Interestingly, looks like Robocopy may have been updated last week, maybe this was part of the change.

![image](https://github.com/tjscience/RoboSharp/assets/20431767/f9817609-672b-4d42-9f03-b3e8b839d51c)

so the options are leave it (do not report extras unless requested, and modify the unit test to always declare them to avoid issue in future), or match current robocopy functionality and have RoboMover also always report extras.

**Comment by PCAssistSoftware** [comment]
its a shame Microsoft don't do release notes so we know what they change when they update robocopy.exe!

Happy for you to do whatever you think is best in relation to the tests

**Comment by RFBomb** [comment]
already pushed the commit that ensures extras are reported. I'm satisfied with this PR at this point

**Comment by PCAssistSoftware** [comment]
> already pushed the commit that ensures extras are reported. I'm satisfied with this PR at this point

previous 5 tests which were failing now passed okay, but getting different ones failing for net472

![image](https://github.com/tjscience/RoboSharp/assets/10872799/4db8aad8-b080-493b-ae6b-d91363903b80)

**Comment by PCAssistSoftware** [comment]
all tests now completing after last commit :)
