### ISSUE TITLE
Using Debugger.Instance.DebugMessageEvent in VB.NET

### ISSUE THREAD

**Issue by eliaspizarro** [tjscience/RoboSharp#21]
I've a VB.NET Winform Project with Robosharp, I want to use Debugger.Instance.DebugMessageEvent, but I can't because i don't know how pass from delagate to event, I know it's a delegate method.

If I go to the 'DebugMessageEvent' definition from VB Proj (Auto-Converted from the DLL called RoboSharp), I get the follow code:

```
Public Class Debugger
    Public DebugMessageEvent As EventHandler(Of DebugMessageArgs)

    Public Shared ReadOnly Property Instance As Debugger

    Public Class DebugMessageArgs
        Inherits EventArgs

        Public Sub New()

        Public Property Message As Object
    End Class
End Class
```

## My VB Project (Doesn't Work)
This is the first test, at the end I tried other methods
![vb dll](https://cloud.githubusercontent.com/assets/8431845/20654892/27426880-b4fc-11e6-80bf-eab1f2d9a89c.png)

```
Imports RoboSharp
Public Class myclass
    ...
    Private Sub backup(...)
        AddHandler Debugger.Instance.DebugMessageEvent, AddressOf console_DebugMessageEvent
        ...
    End Sub
    ...
    Private Sub console_DebugMessageEvent(sender As Object, e As Debugger.DebugMessageArgs)
        Console.WriteLine(e.Message)
    End Sub
    ...
End Class
```
## Another C# Project (Works)

This is a Winform project with C#
![csharp dll](https://cloud.githubusercontent.com/assets/8431845/20654891/27427316-b4fc-11e6-95e9-0218ffaf8d54.png)
```
using RoboSharp;
public partial class myclass : Form
{
    ...
    private void backup()
    {
        Debugger.Instance.DebugMessageEvent += console_DebugMessageEvent;
        ...
    }
    ...

    void console_DebugMessageEvent(object sender, Debugger.DebugMessageArgs e)
    {
        Console.WriteLine(e.Message);
    }
    ...
}
```

## Your DLL C# Code

```
using System;
namespace RoboSharp
{
    public sealed class Debugger
    {
        private static readonly Lazy<Debugger> instance = new Lazy<Debugger>(() => new Debugger());

        private Debugger()
        {

        }

        public static Debugger Instance
        {
            get { return instance.Value; }
        }

        public EventHandler<DebugMessageArgs> DebugMessageEvent;

        public class DebugMessageArgs : EventArgs
        {
            public object Message { get; set; }
        }

        private void RaiseDebugMessageEvent(object message)
        {
            DebugMessageEvent?.Invoke(this, new DebugMessageArgs
            {
                Message = message
            });
        }

        internal void DebugMessage(object data)
        {
            RaiseDebugMessageEvent(data);
        }
    }
}
```

All the rest of DLL functions works as expected. Please advice, I don't want to change the code of the DLL, just the VB.NET code

## Some unsuccessful tests

Pass Visual Studio verification, but others background process associated to RoboSharp send an exit with the event OnCommandCompleted. There is an extrange behavior when I use the follow code but with:

```
    ...
    Private Sub console_DebugMessageEvent(sender As Object, e As Debugger.DebugMessageArgs)
        msgbox("Consola RoboSharp: " & e.Message)
    End Sub
    ...
```
They pass the values, but the others events not.

### New EventHandler
```
Imports RoboSharp
Public Class myclass
    ...
    Private Sub backup(...)
        Debugger.Instance.DebugMessageEvent = New EventHandler(Of Debugger.DebugMessageArgs)(AddressOf console_DebugMessageEvent)
        ...
    End Sub
    ...
    Private Sub console_DebugMessageEvent(sender As Object, e As Debugger.DebugMessageArgs)
        Console.WriteLine("Consola RoboSharp: " & e.Message)
    End Sub
    ...
End Class
```
### DirectCast

```
Imports RoboSharp
Public Class myclass
    ...
    Private Sub backup(...)
        Debugger.Instance.DebugMessageEvent = DirectCast(System.Delegate.Combine(Debugger.Instance.DebugMessageEvent, DirectCast(AddressOf console_DebugMessageEvent, EventHandler(Of Debugger.DebugMessageArgs))), EventHandler(Of Debugger.DebugMessageArgs))
        ...
    End Sub
    ...
    Private Sub console_DebugMessageEvent(sender As Object, e As Debugger.DebugMessageArgs)
        Console.WriteLine("Consola RoboSharp: " & e.Message)
    End Sub
    ...
End Class
```

I don't know if it's a Issue or a Request, because the easy way to fix is implement an event on the Robosharp side.

Regards,

**Comment by tjscience** [comment]
Hi @eliaspizarro,

Sorry, I am not going to be much help here as I know nothing of VB.NET. If you are still having this issue, you might want to try asking for some help on stackoverflow.

Thanks,
tjscience

**Comment by absinghal** [comment]
Hi

Not sure if this is too late. But posting this for the benefit of others who reach here.

Used following to hook:
Debugger.Instance.DebugMessageEvent = Sub(sender As Object, e As DebugMessageArgs)
                                                      Trace.WriteLine(e.Message)
                                                  End Sub
We can also use 
Debugger.Instance.DebugMessageEvent = AddressOf _EventHandler_

Hope it helps.

Thanks
