### ISSUE TITLE
IFileCopier & FileInfo.LastWriteTime

### ISSUE THREAD

**Issue by RFBomb** [tjscience/RoboSharp#211]
I was testing my library that extensions was written for, and I found an interesting nuance that I think is worthy of discussion. 

When using `FileInfo.CopyTo(string destination)` ( or `File.CopyTo(string source, string destination)` ) it copies the file and all attributes synchronously. The `IFileCopier` class was meant to introduce an async method for this, platform agnostic using `StreamedCopier` and windows-optimized via `Windows.CopyFileEx`

My unit test was verifying that the copied file matches the date and times on the source file, and I couldn't get it to pass. Whereas the unit test that used CopyTo() passed just fine. 

I swapped out my IFileCopierFactory to use CopyFileEx instead of the StreamedCopier, and found that CopyFileEx will write out the source details to the destination file (such as last write time), while StreamedCopier does not. (CopyFileEx passes, StreamedCopier does not).

SO the discussion here is essentially: Should StreamedCopier emulate CopyFileEx (and `File.CopyTo`) by writing out the source file's attributes to the destination file? 

FileInfo Properties:
- Attributes
- CreationTime ( we'd have to investigate this one, unsure at the moment if this can be newer than last write time )
- LastAccessTime (time of writing - should match the write time I think?)
- LastWriteTime (currently this is the time the copy operation completes, instead of the time the source was last written to)

My concern here is that StreamedCopier could introduce a scenario where files are always copied because the `LastWriteTime` is always newer than the source file.

**Comment by PCAssistSoftware** [comment]
Hi Robert

Just a quick initial response to say I will read through this and get back to you properly in the next few days, currently tied up with Christmas bits and pieces.  All the best for now

**Comment by RFBomb** [comment]
Yes I'm off for next week or two myself, I was just finalizing some code on my project when I caught it. I have a unit test set up that can prove it out and can make a repo to discuss. 

I don't plan to touch this till I'm back in the office either! Happy holidays!

**Comment by PCAssistSoftware** [comment]
And the same to you :)

Just had a few minutes so been reading through.  To be honest I haven't really used the extensions you created, all my main apps currently use the original robocopy side of things, but I really do need to find time in the new year to test it out more fully as some of your newer methods may work better for me anyway.

My initial thoughts (again without testing anything myself) would be that it should perhaps behave similarly to how robocopy works in that you can choose whether you wish to copy the file / folder attributes, especially in relation to important dates such as last modified because you may (as you mention) use that to determine if files need copying again or not if size same and you are just going on dates.

**Comment by RFBomb** [comment]
As I've noted before, I'm using RoboSharp as a basis for a dynamic sync library for caching network files locally and for creating file batches of various user-selected items to copy to some arbitrary destination. So the extensions I've written were for custom IRoboCommands for not only that purpose, but with the idea that RoboSharp could become cross-platform via a custom command object (which is partially what I think occurred in #178). This would also give more direct control to a caller, instead of running the operation via a separate process. 

So I think it's best to mimick native copy operations with regard to write times and other attributes. It's something I hadn't considered prior to my other project producing inconsistent results though. 

As far as 'LastModifiedDate', I could've sworn that was a property available for Files, but I'm feeling like I gaslit myself since all documentation I find says 'LastWriteTime'. Yet i once wrote a comment "use LastWriteTime instead of LastModifyDate because LastModifyDate may be older than LastWriteTime when an old file was copied to a new destination"
