### ISSUE TITLE
Exclude directories with a space in name

### ISSUE THREAD

**Issue by phenomarc** [tjscience/RoboSharp#23]
I'm trying to exclude a Directory that contains a space in his name.
It works with: "Folder1 Folder2 ...", but not with: "Folder 1 Folder2..."
It reads "Folder" and "1" as a different folders, but they are only one.
Is there a option to change the separator from space to other element, like $?

**Comment by tjscience** [comment]
Hi @phenomarc,

If you have spaces in folders, you need to surround them with quotes. Using your example above, you should have: 

`"\"Folder 1\" Folder2"`

Thanks for using RoboSharp!
tjscience
