### ISSUE TITLE
Only the top level directory is copied.

### ISSUE THREAD

**Issue by eriko** [tjscience/RoboSharp#24]
The following is the configuration that RoboSharp logs.
"c:\temp\STA\fall-17-archive\vertevo" "c:\temp\LTA\2017-vertevo" "*.*" /COPY:DAT /DCOPY:DA /SEC /MIR

"c:\temp\STA\fall-17-archive\vertevo" is a directory structure of empty directories (empty in test may or may not be empty in production).  When I feed that configuration to RoboCopy on the cli it mirrors the structure correctly.  If I use RoboSharp it only Copies the top level of the structure.

The ACl structure is a little complex so I thought maybe the executable need to be run with administrator rights but that did not seem to have an effect.

Any thoughts?

**Comment by tjscience** [comment]
I am not seeing any issue with this. I tested by mirroring a pretty dense directory tree over using Mirror and had no issues. Here are some things to note. For mirroring with robosharp, all you need to do is specify the source, destination and enable the Mirror flag. That is the simplest way to do a mirror command. Are you setting other options? If so, which ones? Can you post the portion of your code where you setup the RoboCommand? Here is my setup which is working:

```c#
RoboCommand command = new RoboCommand();
command.CopyOptions.Source = @"<path to source>";
command.CopyOptions.Destination = @"<path to destination>";
command.CopyOptions.Mirror = true;
command.OnCommandCompleted += Command_OnCommandCompleted;
command.OnFileProcessed += Command_OnFileProcessed;
command.Start();
```

Also, these are the logged options from RoboSharp:

`Options : *.* /BYTES /S /E /DCOPY:DA /COPY:DAT /PURGE /MIR /R:0 /W:30`

**Comment by eriko** [comment]
That looks just like mine.  I am sure the issue is on my end but I figured I would check just to be sure. One other thing I have noticed it that the logging does not seem to work for me.  I wonder if that is related. The file is not created or if manually created updated.  I have changed all my On... methods to just log to Console as the app is a purely commandline.

Anyways thanks for the reply and for the tool.

```

    RoboCommand archive = new RoboCommand();
                archive.OnFileProcessed += copy_OnFileProcessed;
                archive.OnCommandError += copy_OnCommandError;
                archive.OnError += copy_OnError;
                archive.OnCopyProgressChanged += copy_OnCopyProgressChanged;
                archive.OnCommandCompleted += copy_OnCommandCompleted;
                //logging  options
                archive.LoggingOptions.LogPath = log_location;
                archive.LoggingOptions.VerboseOutput = true;
                // copy options
                archive.CopyOptions.Source = target;
                archive.CopyOptions.Destination = destination;
                archive.CopyOptions.CopyFilesWithSecurity = true;
                archive.CopyOptions.Mirror = true;
                // select options
                //archive.SelectionOptions.ExcludeDirectories = " Cubbies Students Workspace " ;
                // retry options
                archive.RetryOptions.RetryCount = 10;
                archive.RetryOptions.RetryWaitTime = 10;
                command.Start();
```

**Comment by tjscience** [comment]
There is an issue where when you set the logpath, it will not raise individual events. I will look into this but you can simply comment out that line and it should work. Also, you don't really need verbose output if you are raising events.

**Comment by eriko** [comment]
Ok thanks.  I had added the logging before I when back and added the event stuff while I tried to figure out what I did wrong.  

When I figure out my issue I will come back update this.  For now I an going to close it.
