### ISSUE TITLE
OnFileProcessed event not thrown

### ISSUE THREAD

**Issue by ram2000** [tjscience/RoboSharp#26]
The OnFileProcessed event is not thrown in case that a the AppendLogPath property is used.

`  public async Task Backup(string SourceFolder , string DestinationFolder, bool runAsBackground = true)
        {
            await Task.Factory.StartNew(() =>
            {
       
                if (string.IsNullOrEmpty(SourceFolder) || string.IsNullOrEmpty(DestinationFolder))
                    throw new FileNotFoundException("Folder is null or empty");
                
                if(!Directory.Exists(SourceFolder) )
                    throw new FileNotFoundException("SourceFolder does not exists");

                if (!Directory.Exists(DestinationFolder))
                    throw new FileNotFoundException("DestinationFolder does not exists");

                RoboCom?.Dispose();

                RoboCom = new RoboCommand();

                // Backup Path 
                var logFileWithPath = Path.Combine(DestinationFolder, "Backup.log");
                File.AppendAllText(logFileWithPath, $"{Environment.NewLine}{Environment.NewLine}+++++++        Backup [Started] {DateTime.Now}         +++++++{Environment.NewLine}");
                RoboCom.LoggingOptions.AppendLogPath = logFileWithPath;
                //RoboCom.LoggingOptions.ShowEstimatedTimeOfArrival = true;
                //RoboCom.LoggingOptions.NoProgress = true;

                // Signal Progress 
                CopyOnProgress = true;

                // searches the current directory and sub directory
                TotalFiles = Directory.GetFiles(Source, "*", SearchOption.AllDirectories).Length;

                // events
                RoboCom.OnFileProcessed += backup_OnFileProcessed;
                RoboCom.OnCommandCompleted += backup_OnCommandCompleted;
                RoboCom.OnCopyProgressChanged += Backup_OnCopyProgressChanged;
                RoboCom.OnError += RoboCom_OnError;

                // copy options
                RoboCom.CopyOptions.Source = this.Source;
                RoboCom.CopyOptions.Destination = this.Destination;
                RoboCom.CopyOptions.MultiThreadedCopiesCount = runAsBackground ? 2 : 8;
                RoboCom.CopyOptions.CopySubdirectories = true;
                RoboCom.CopyOptions.UseUnbufferedIo = true;
               
                // retry options
                RoboCom.RetryOptions.RetryCount = 1;
                RoboCom.RetryOptions.RetryWaitTime = 2;
                RoboCom.Start();
            });`

**Comment by tjscience** [comment]
It is strange, I though that I left a comment here awhile... Sorry about that! I think that what you are after can be achieved by setting the following flag:

`RoboCom.LoggingOptions.OutputToRoboSharpAndLog = true;`

Sorry this is so late :)
