### ISSUE TITLE
Blocking until copy complete

### ISSUE THREAD

**Issue by mrichman** [tjscience/RoboSharp#3]
How can I block after calling `Start()` such that my function using RoboSharp doesn't return until the file copy operation is complete?

I've tried something like this in my WPF app, but after a while I start getting several `OutOfMemoryException` thrown. I'm assuming it's that `BeginInvoke()` call in the loop.

```
var copydone = false;

...

robocopy.OnCommandCompleted += (sender, args) =>
{
copydone = true;
};

...

while (copydone == false)
{
    Dispatcher.CurrentDispatcher.BeginInvoke(new Action(() => Task.Delay(500)));                        
}
````

I'm also running a several simultaneous instances of this (between 3 and 5), not sure if that matters.

**Comment by mrichman** [comment]
Update: I was able to produce the results I was after using `AutoResetEvent`, calling `WaitOne()` just after `RoboCommand.Start()` and setting it in the event handler.

**Comment by tjscience** [comment]
@mrichman glad you were able to resolve your issue. Although, I am not completely clear as to what was going on. The OnCommandCompleted event should only fire after the copy command has completed.

**Comment by mrichman** [comment]
The issue was that Start() is a non-blocking operation.

**Comment by redwo1f** [comment]
@mrichman Can you post your code please?  I am running into the same problem, multiple copy.Start() operations and the copy_OnCommandCompleted being run before all are complete.
