### ISSUE TITLE
TaskParallelLibrary in .NET 3.5 creates dependency issue

### ISSUE THREAD

**Issue by nielwestover** [tjscience/RoboSharp#31]
My project is using .NET 4.6.  I was getting errors because your project pulls in TaskParallelLibrary from NuGet, and it was causing name conflicts with my project.  I upgraded your project to 4.6 and removed the TaskParallelLibrary dependency, because System.Threading.Tasks is included now.

Great product by the way!  I'd love to be able to use the NuGet version but I can't until you go to a later .NET framework.

**Comment by tjscience** [comment]
Hi Niel,

Thanks for using RoboSharp and for the kind words! The library used to target a higher framework, but there was a request to be able to target 3.5 (#27). Not sure what to do here now. My gut feeling is that RoboSharp should evolve with .NET and use a more recent version. I am just not sure how to support both. Let me think about this and get back to you.

**Comment by INYSRMCGCG** [comment]
I agree with @nielwestover and @bruceburge 
The current nuget package causes issues and rolling back to 1.0.25 was the only way to get it to work again

**Comment by sManWorks** [comment]
I agree with @nielwestover and @bruceburge 
Rolling back to 1.0.25 version was the only way to get the build to compile

**Comment by tjscience** [comment]
Hi,

I have created a separate branch and nuget package that targets .NET 3.5. I have updated the master branch to target .NET 4.5 and updated the nuget package as well. Thanks again for using RoboSharp!

**Comment by generik0** [comment]
@tjscience i seam to be having an issue with net4. I have to role back to V1.0.25 also due to the TaskParallelLibrary. Have you stopped supporting net4?

**Comment by generik0** [comment]
@bruceburgethe but the main branch can do both net4 and net35. I have added a PR spike for discussion

**Comment by bruceburge** [comment]
@generik0 I want to make it clear, that I don't make any choices about this project, or what pull request or accepted.  I just used the project, and have contributed to a very small amount of code.

But from my perspective, it seems you are requesting a significant amount of effort, that will require moving the project to a format only supported by visual 2017 forward, the projects multi targeting configuration would have to be managed by manually editing and managing the .csproj file.

And then, to make the multi targeting work, you would have to add framework specific pre compile directives in places that have conflicts? 

Example below from your PR
```
#if NET40
                backupTask = Task.Factory.StartNew(() =>
#else
                backupTask = Task.Run(() =>
#endif
```
Is that assessment accurate? 

If it is, the next question would be, how does that really benefit those using the project, and at what cost to the maintainer and contributors of the project? 

in my own personal opinion adding inline directives is generally just a time bomb waiting to happen, now you are having to trace logic across different version of the framework, and how these directive substitutions will handle what you are doing, functionally equivalent, still can have drastic side effects for instance

> "Task.Run(Action) by default does not allow child tasks started with the TaskCreationOptions.AttachedToParent option to attach to the current Task instance, whereas StartNew(Action) does. "

But again, this isn't my call to make, I'm just expressing my opinion on the matter.

**Comment by generik0** [comment]
Hi @bruceburge 
Thanks for your thoughts. You are welcome to write on the Spike PR.
I agere with all that you are saying in principle. But would like to express  that the new .net standard template and frameworks target  is really Great! It allows multple frameworks, with the minimum of fuss. I have some private packages supplering net4, net45 and netstandard 2.
It works!!! And builds the Nuget package also...

So my opinion, this is the format for the future, and forget the rest... also if robosharp wants to netcore / net standard soon. This is the first step.

You are right about the compile switch, but I don’t see an issue with it.
I have the PR running on net40 with my own build, it works great. But do you see issues with the task start? Memory leaks or functional issues?

Thanks for your time, Regards, G.

**Comment by bruceburge** [comment]
I don't know of a specific problem with Task.Run vs. Task.Factory.StartNew just pointing out that though functionally the same, they are not identical, and that is a concern that has to be cascaded down to everything touching it, and so will every place that there is a difference, I don't think the conditional sniping to change out the incompatibilities like this, will work when you apply it on a large scale.

That said, I think like anything with the right amount time, and precautions it could be made to work, but I'm not sure having it on one project makes for a better experience, you trade maintaining three projects, for maintaining three projects worth of functionality in one, with a large number of directive conditional statements. 

I think this method might be great if you were starting a new project with it, and you made these choices as a part of your design process, but back porting this, just sounds painful.

**Comment by generik0** [comment]
Hi @bruceburge 
All very good points. But i cant find a issue use task.factory.start anywhere. Task.factory.start tpl arrivef  in net4 and task.run is just shorthand for task.factory.Start with specific arguments. Hence the task.run could be actually be changed in the net45  version: [regarding-usage-of-task-start-task-run-and-task-factory-startnew](https://stackoverflow.com/questions/29693362/regarding-usage-of-task-start-task-run-and-task-factory-Startende).
Also i did the net standard convesion in the spike. It is very easy to maintain and test.
But net core might be best as a separate library. Depending on the changes needed.
My experience so far is That there are more changes between net4 and net45 than between net45 and net standard. There are missing libraries between net452 and standard. But the gap is getting smaller and smaller.

My point is using the net35 library for net4 is not correct. But i understand your poi ts, maybe the net45 should be changes to net4 and use:
```c#
Task.Factory.StartNew(
    action, 
    CancellationToken.None, 
    TaskCreationOptions.DenyChildAttach, 
    TaskScheduler.Default);
```


Replacing task.run

**Comment by bruceburge** [comment]
As for the hot swapping the two, see [here]https://stackoverflow.com/questions/41788529/why-task-factory-startnew-returns-immediately-while-task-run-does-not) and [here](https://blogs.msdn.microsoft.com/pfxteam/2011/10/24/task-run-vs-task-factory-startnew/) and yes, the application could be specifically changed, to remove using the shorthand provided for in the newer version of .net, but why? 

The longer we discuss this, the more to me seems to have less value, and only serves to make the code base harder to manage, and more error prone. 

But I understand what you want, I believe you understand my viewpoint on the matter, both are rather moot as it ultimately Terry who would decided. 

I'll leave things as they stand, and let others continue the conversation if they see the need.
