### ISSUE TITLE
Separate ErrorEventArgs into two fields

### ISSUE THREAD

**Issue by bruceburge** [tjscience/RoboSharp#33]
One for the message provided, a second for the code returned from RoboCopy (or Null) 
this would make it a lot easier than having to reparse the string each time the end user has a copy exception,

**Comment by bernatpi** [comment]
That's a tricky one. I've tried to add the exit code from RoboCopy.exe to `ErrorEventArgs`, but the events `OnError` and `OnCommandError` are fired when RoboCopy.exe is still running. It's not until ` process.WaitForExit();` that we can retrieve the exit code from RoboCopy.exe, Thus, the best I can come up with is to add the RoboCopy exit code as an argument of the `OnCommandCompleted` event.

Writing this, I've just realized that maybe you are refering to the error codes that are written on the `ErrorEventArgs` string (such as `2020/02/17 12:48:41 ERROR 5 (0x00000005) Copiando archivo C:\temp\pdf\PO3003931639.pdf Access is denied.`), and not the proper exit code returned by RoboCopy.exe as seen on the official [docs](https://ss64.com/nt/robocopy-exit.html). So I think I will do both: include the parsed error code in `ErrorEventArgs` as an integer and the RoboCopy.exe exit code in ´RoboCommandCompletedEventArgs´.
