### ISSUE TITLE
Supported languages of RoboCopy

### ISSUE THREAD

**Issue by alex-becker-startp** [tjscience/RoboSharp#38]
Hello,

when I look at the sources, it seems only the englich (british or US) language is supported,
because the console output of RoboCopy is parsed against keywords.

I see some ways how this could be internationalized:
1) parse the Robocopy.exe.mui file matching to the current culture and use the strings from there
2) provide public properties for the keywords so the user can edit them
3) provide a property to the path of robocopy.exe so the user can place a copy of robocopy along with a matching en-US mui file in a separate folder

Maybe you have some better idea?
Alex.

**Comment by tjscience** [comment]
If you have the time and need, can you create a pull request?

**Comment by alex-becker-startp** [comment]
I did this before and you've accepted the [pull request](https://github.com/tjscience/RoboSharp/pull/39).

**Comment by bruceburge** [comment]
@alex-becker-startp  it helps everyone in a project, when you have an issue, and make a pull request related to it, that you reference it in the message, you can do this by typing the #xx of your pull request number, in your case 39  it will show as #39  

I'm guessing this is why there was some confusion.

**Comment by ehrenfeu** [comment]
Since PR #39 is merged, this issue could safely be closed, no?

**Comment by alex-becker-startp** [comment]
Sure, I'll close it.
