### ISSUE TITLE
directoryCopyFlags incorrect default value

### ISSUE THREAD

**Issue by greeny1000** [tjscience/RoboSharp#4]
Hi,
I'm trying out Robosharp (i'm also new to Robocopy) and had problems getting it to work

I think the default value of  line 48, copyoptions.cs 
        private string directoryCopyFlags = "DA";
is incorrect. I think the only valid option is "T"

If the public property DirectoryCopyFlags is not set by the user, then Robosharp runs & exits but does not copy any files & does not report an error. This stumped me for quite a while.

If the commandline version is run using the option string generated by Robosharp an error is reported. 

Cheers

**Comment by tjscience** [comment]
Copy option have the following flags to use:
D     Data 
A     Attributes 
T     Time stamps
S     NTFS access control list (ACL)
O    Owner information
U     Auditing information
The default value for CopyFlags is DAT (data, attributes, and time stamps).
/IS - Includes the same files.
/IT - Includes "tweaked" files.

You should be able to use any combination of these flags or not set it at all. I will test when I get a chance.

**Comment by greeny1000** [comment]
Hi,
I'm not referring to CopyOptions, but DirectoryCopyOptions which afaik can only take "T"
but defaults to "DA"  at  line 48, copyoptions.cs 
Therefore if not set by the user it defaults to "DA" and any copy fails(but does not give an error).

Cheers

**Comment by rralston4** [comment]
I made that change also when I was looking at the class.

**Comment by tjscience** [comment]
With robocopy, the default flags for DCOPY are actually DA. I am not sure why the documentation from microsoft shows different, but these are the default flags. You can see this by executing robocopy with no options, with the source and target directories the same. (e.g. robocopy c:\test c:\test).
