### ISSUE TITLE
Options COPY_FLAGS & DIRECTORY_COPY_FLAGS are always added even if empty

### ISSUE THREAD

**Issue by greeny1000** [tjscience/RoboSharp#5]
Hi,

In CopyOtions.cs  lines 280/281
`options.Append(string.Format(COPY_FLAGS, CopyFlags.CleanOptionInput()));`
`options.Append(string.Format(DIRECTORY_COPY_FLAGS,DirectoryCopyFlags.CleanOptionInput()));`

are always added even if the properties CopyFlags & DirectoryCopyFlags are empty.
Should they be conditionally added similar to later options?
e.g. 
`if (!string.IsNullOrWhiteSpace(CopyFlags))`
`    options.Append(string.Format(COPY_FLAGS, CopyFlags.CleanOptionInput())); `
`if (!string.IsNullOrWhiteSpace(DirectoryCopyFlags))`
`    options.Append(string.Format(DIRECTORY_COPY_FLAGS,DirectoryCopyFlags.CleanOptionInput()));`

Cheers

**Comment by tjscience** [comment]
Hmm.. that is strange. I will test this out as soon as I get a chance.

**Comment by mrichman** [comment]
Funny, I was about to open a related issue. `/DCOPY:DA` and `/J` (and others) are not supported on older versions of Windows. I've had to check the OS version and do some logic around these:

```
if (Environment.OSVersion.Version < new Version(6, 2))
                        robocopy.CopyOptions.DirectoryCopyFlags = "T";

if(Environment.OSVersion.Version >= new Version(6, 2))
                        robocopy.CopyOptions.UseUnbufferedIo = true;
```

**Comment by rralston4** [comment]
I saw the same issue (BOTH)… and I’m on Windows 10.  I had done the update Windows 7 to Windows 10 during the free upgrade deal.

**Comment by tjscience** [comment]
@greeny1000 I have already changed the way robocopy handles the copy flags/ dcopy flags settings. I will be checking those in shortly.

**Comment by tjscience** [comment]
Regarding the issues that arise from versions, this would be very hard to handle all of the cases where robocopy has changed from windows version to version. I will try to come up with a more generic way to handle these situations where it does not cause robocopy to fail while executing. Maybe it would be more straight forward to simply have version checking in robosharp that handles this. For that to even be possible, I would need all of the options for each version. If you guys have time, and are able to pull the options from different versions, please attach them to a comment in this issue. I already have the settings for versions 6.1.7601 and 10.0.10586 You can obtain all of the settings by executing this command: 
`robocopy /? >> rcopyoptions.txt`

**Comment by tjscience** [comment]
robocopy options for windows version 6.1.7601
[rcopyoptions.txt](https://github.com/tjscience/RoboSharp/files/183102/rcopyoptions.txt)

**Comment by tjscience** [comment]
robocopy options for windows version 10.0.10586
[rcopyoptions-10.0.10586.txt](https://github.com/tjscience/RoboSharp/files/183106/rcopyoptions-10.0.10586.txt)

**Comment by ehrenfeu** [comment]
For the record and / or completeness reasons, the robocopy version shipped with Windows 7 reports a file version of `5.1.10.1027` and prints exactly the **same help message** as the one listed above from `6.1.7601`.

The exact version can easily be determined using the following PowerShell command:
```powershell
$(Get-Command robocopy).FileVersionInfo.FileVersion
```
