### ISSUE TITLE
Overall progress

### ISSUE THREAD

**Issue by wingers999** [tjscience/RoboSharp#50]
Hi

Would there possibly be a way to show overall progress of the whole copy job as well as just progress of current file - doesn't need to be perfectly accurate, but would be nice when copying lots of data from server A to server B to know progress

Even nicer would be an estimate of remaining time but suspect that may be a lot more difficult

Finally great work with this project - very useful :)

**Comment by wingers999** [comment]
Hi, is this project still being maintained?

What I would love to see is overall progress not just per file progress

Using RoboCopy in powershell/command line you can use the /L switch for "Staging" which will then return number of files/folders that need copying and the size

I think this could be then shown as overall progress just based on file count - using progress bar set to above file account as maximum and then incrementing progress bar by 1 each time it gets to  void copy_OnFileProcessed or  void copy_OnCopyProgressChanged

Now I am no expert on C# programming - prefer working in VB but was hoping someone might have ideas about implementing this

Sorry I can't provide a Pull request - only ideas at this stage

Thanks

**Comment by tjscience** [comment]
Thanks for using the project and contributing ideas. At this time, I am not able to maintain the library as much as would like. I welcome the community to provide changes ad features and I will try to put some more time in to fix any critical issues and hopefully work on some of these requests.

**Comment by wingers999** [comment]
I have found a way to implement this in a VB port of this project - basically running RoboCopy the first time using /L switch and then using the Extended Results from pull request https://github.com/tjscience/RoboSharp/pull/40 - you can then create a progress bar based on the total size of files that need copying compared to current total copied in copy_OnFileProcessed - works fine for me so far :)
