### ISSUE TITLE
How to add file list to copy

### ISSUE THREAD

**Issue by oakdemirci** [tjscience/RoboSharp#55]
Thanks for the nuget.
How can we include File list as in the command, I could not find a way or a sample. 
robocopy <Source> <Destination> [<File>[ ...]] [<Options>]

Regards.

**Comment by bernatpi** [comment]
The `FileFilter` is now an `IEnumerable<string>`, so one way is to create an array:

`var command = new RoboCommand();`
`command.CopyOptions.FileFilter = new[] { "file1.txt", "file2.txt" };`
