### ISSUE TITLE
FileFilter not working. With solution.

### ISSUE THREAD

**Issue by skykharkov** [tjscience/RoboSharp#56]
Hi. Thank you for this wrapper.
In short, FileFilter not working. Just need change 

`
options.Append($"\"{FileFilter}\" ");
`

to 

`
options.Append($"{FileFilter} ");
`

in CopyOptions.cs for fix this.

**Comment by bruceburge** [comment]
Can you please be a bit more specific, as to what file you are talking about, or better yet, make a pull request with your suggested fix?

**Comment by skykharkov** [comment]
Hi. If I want backup specific files (for example only *,jpg and *,png) I set 
`FileFilter = "*.jpg *.png"`
In result options it placed with quotes because you specify "\"". But it not working. Because file extension in quotes assume like one, big extension. If we remove quotes all working fine. Example:

robocopy "C:\source" "C:\target" "*.jpg *.png" - wrong
robocopy "C:\source" "C:\target" *.jpg *.png - correct

**Comment by bruceburge** [comment]
In the long term, the copyoptions string should likely be replaced with a list, and then insure each option is properly escaped with quotes.

**Comment by BernatPi** [comment]
I'm currently changing the FileFilter string into a list. Giving that it is a breaking change, I am considering marking the current FileFilter string as obsolete to issue a warning and create a new property (FileFilterList) that works as expected, properly quoting each item. What do you think?

**Comment by wingers999** [comment]
@bernatpi - excellent work, just made your changes to my offline version and it worked perfectly, hopefully your pull request will be accepted :)

**Comment by wingers999** [comment]
Suggestion to improve this, as current solution doesn't cope if you supply a file name with a space in e.g "test doc.pdf", and perhaps also useful to strip out any duplicates, please see my amendment below for RoboSharp.BackupApp/MainWindow.xaml.cs

Change:-

```
var fileFilterItems = Regex.Matches(FileFilter.Text, @"[\""].+?[\""]|[^ ]+")
                .Cast<Match>()
                .Select(m => m.Value);
```

To:-

```
  var values = Regex.Matches(FileFilter.Text, @"(?nx)\s*""(?'v'[^""]*?)""\s*,? | \s*(?'v'\S+)\s*,?")
                            .Cast<Match>()
                            .Select(m => m.Groups["v"].Value);

            IEnumerable<string> fileFilterItems = values.Distinct();
```

**Comment by bernatpi** [comment]
Maybe I'm missing something, but the current solution already copes for filenames with spaces if they are quoted. Currently, if you supply `test doc.pdf` it treats it like two separate files, but if you supply `"test doc.pdf"` it treats it like one single file with a whitespace, as I think it should be. Moreover, you can combine quoted and unquoted filenames: `test doc.pdf "test doc.pdf"` and the current solution will properly quote the three files as `"test" "doc.pdf" "test doc.pdf"`, same as yours.

**Comment by wingers999** [comment]
Okay was only a suggestion!  

Try something like below  and it doesn't work

".doc" "test.xls", ".doc","me.pdf" .doc "my file.txt"

Items have to be separated by a space, if as above you separate using commas or commas and spaces then you end up with combining two of the entries

".doc" "test.xls" "," ".doc" ","me.pdf" ".doc" "my file.txt"

With mine it handled comma, space, comma and space, and also removed the duplicate items

".doc" "test.xls" "me.pdf" "my file.txt"

**Comment by bernatpi** [comment]
Oh, I see. You are absolutely right, I did not take into account separators other than whitespace. If we add `,` as a valid separator maybe we should add `;` too.

**Comment by wingers999** [comment]
Have amended my version above so it can also handle semicolon ;

**Comment by bernatpi** [comment]
I'm having second thoughts, for `,` and `;` are valid filename characters that the windows terminal accepts without quotation marks. I mean, windows users are aware that filenames with spaces have to be escaped with quotes, but with this change we are asking them to also quote filenames containing `,` and/or `;`, and I think that's against windows "common knowledge". I mean, if a user wants to copy the file `ab;c.txt` he will probably type it without quotes and end up copying `ab` and `c.txt`. What do you think?

**Comment by wingers999** [comment]
I certainly see your point, but in all my many years working in IT I have never ever come across a filename having either a comma or a semicolon in it

**Comment by bernatpi** [comment]
Me neither, really. I'm keeping this change in my offline copy, but I have mixed feelings about making a pull request.

**Comment by wingers999** [comment]
Just posting this here for future reference, but below solution copes with comma (,), semicolon (;) and whitespace ( ) as separators, BUT can also handle rare cases where those are part of the file name as well

```
var text = "\".doc\" \"te;st.xls\", \"test.xls\", \".doc\",\"me.pdf\", \"test file.doc\".doc \".doc\";\".xls\"";
Console.WriteLine(text); // => ".doc" "test.xls", ".doc","me.pdf", "test file.doc".doc ".doc" ".xls"
var pattern = "\"(?<ext>[^\"]+)\"|(?<ext>[^\\s,;]+)";
var results = Regex.Matches(text, pattern)
        .Cast<Match>()
        .Select(x => x.Groups["ext"].Value)
        .Distinct();
Console.WriteLine(string.Join("\n", results));

```
