### ISSUE TITLE
RoboSharp Going Forward...

### ISSUE THREAD

**Issue by tjscience** [tjscience/RoboSharp#63]
Hi All, 

There has been a lot of confusion and back and forth on the topic of how to properly structure the RoboSharp project going forward, mainly with respect to support for older targets and moving into the future by utilizing the newer targets. While I do agree that we should be moving toward the future, one of the (albeit invisible) tenants of this project was to design it in such a way that it would be backward compatible to a pretty good degree with older versions of .NET. So, I do not want to simply force everyone in the future to use VS 2017 and a .NET Standard, for example. 

That being said, I would like to open up this topic for discussion from the people that have contributed to this project, use it, or simply want to offer up their two cents. My main goal here is to get a discussion going on how we should structure the project for the future to support modern targets as well as older versions of .NET.

Please, if you have time, let me know what you think...

![image](https://user-images.githubusercontent.com/3706870/44311401-a9064000-a3b4-11e8-96a3-d308f52aeec1.png)

**Comment by wingers999** [comment]
I personally (and I suspect others will disagree) think most projects should support the newest reliable version of .NET available.  I appreciate some people want backward compatibility, but usually newer versions of .NET bring better reliability and new features that projects can make use of to make them even better.  Whatever you decide keep up the good work, as this project is so useful to me

**Comment by eliaspizarro** [comment]
by other hand, older versions of framework provides compatibility like windows server 2003, 2008, ...

**Comment by tjscience** [comment]
I have restructured the app in a much more modern way thanks to some generous contributions! With this new project structure, we have support for: .net standard 2.0, .net core 2.0, .net 4.5, and .net 4.0. If someone needs another framework supported and it is a one-off, they can very easily add that in a clone of the project with it's new structure. I still do not have a handle on how this is going to work in nuget, but I will work that out as I commit.

**Comment by LucasFarley** [comment]
It is a good solution.  Congratulation.

**Comment by rshaporenko** [comment]
Why don't to use Environment.OSVersion Property instead of WMI query SELECT * FROM  Win32_OperatingSystem inside VersionManager class. Sometime that query is failed due to WMI corrupted. Environment.OSVersion should be less vulnerable  way.

**Comment by PCAssistSoftware** [comment]
Not sure this discussion really relevant now? 

Over five years have passed since this topic was started, and the project has definitely developed and moved forward really well during that time, thanks to some fantastic input from some of the contributors we have support for .NET 6.0 and continue to support .NET Framework 4.5.2+ as well, which covers the discussion really of this topic.   

And many new features and improvements have been added too.

Therefore I suggest we close this issue? and will do so shortly unless I hear to the contrary. :)
