### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by marius-stanescu** [tjscience/RoboSharp#66]
I am trying to use the NuGet package in a .NET Core application, but I get the following error:

> NU1701	Package 'RoboSharp 1.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by tjscience** [comment]
Hi @marius-stanescu. Thanks for your interest in the RoboSharp project. We currently do not have a project that supports .NET Core. That being said, there is an open discussion on how to approach this in the future. You can see that in issue #63. Please feel free to add your opinion there.

**Comment by tjscience** [comment]
Sorry, didn't mean to close this!
