### ISSUE TITLE
Robocopy Nuget package description

### ISSUE THREAD

**Issue by bruceburge** [tjscience/RoboSharp#67]
Seems to be a commit message, and not description of project.

![image](https://user-images.githubusercontent.com/6773890/45581714-cff74b00-b868-11e8-93ae-0de406216980.png)

**Comment by tjscience** [comment]
I am not seeing an issue here. Maybe it was fixed with the latest package publish?

![image](https://user-images.githubusercontent.com/3706870/45603481-53947180-b9fa-11e8-9049-c272e709e64c.png)
