### ISSUE TITLE
Copying from C: doesn't work

### ISSUE THREAD

**Issue by chainnnnn** [tjscience/RoboSharp#70]
Copying with the following command doesn't work. It just copies the files of the current directory where the .exe is (in my case the project folder).
`FilesFromC.CopyOptions.Source = "C:";`

**Comment by bernatpi** [comment]
This behavior is explained in the official windows documentation ([link](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths)). Quote: 

> If a file name begins with only a disk designator but not the backslash after the colon, it is interpreted as a relative path to the current directory on the drive with the specified letter.

So yes, `FilesFromC.CopyOptions.Source = "C:";` will be interpreted as the program current directory on drive C. If you want to copy from the drive root you'd have to use `C:\`, with a backslash.

**Comment by bernatpi** [comment]
Closing issue as this is excepted behavior.
