### ISSUE TITLE
LoggingOption.NoProgress must be set to false.

### ISSUE THREAD

**Issue by edalger** [tjscience/RoboSharp#71]
I would like to set:
 _backup.OnCopyProgressChanged += backup_OnCopyProgressChanged;

To use the progress information, LoggingOption.NoProgress must be set to **false**.

This produces a verbose logging where the progress percentage for every Robo Copy made.
I need the percent changed but I don't want it in the log.
Can a change be made to this?
RoboSharp is really great and It's been a solution for my situation.
Ed...

**Comment by wingers999** [comment]
Hi Ed
Please give more details as NoProgress is set to false by default anyway, and progress information can be show in your GUI using e.CurrentFileProgress; which if you look in the sample app is handled as you say in the copy_OnCopyProgressChanged event to show progress of current file

```
 void copy_OnCopyProgressChanged(object sender, CopyProgressEventArgs e)
        {
            Dispatcher.BeginInvoke((Action)(() =>
            {
                FileProgress.Value = e.CurrentFileProgress;
                FileProgressPercent.Text = string.Format("{0}%", e.CurrentFileProgress);
            }));
        }
```

You can also show current file name (e.ProcessedFile.Name;) and current file size (e.ProcessedFile.Size.ToString();)

Using the ExtendedResults added in last commit to the dev branch you can then also shows things such as overall progress based on total size to copy, total number of files to copy / delete.  I do this by first running the copy job with LoggingOptions.ListOnly = True so I can get information on what needs copying / deleting etc from the ExtendedResults, and then use this information to show detailed progress in my GUI when job then running with ListOnly set to True.

Hope this make sense and helps.

**Comment by wingers999** [comment]
You can also access the whole contents of the log file using the new ExtendedResults via e.Results.LogLines and then you can choose what you wish to do with it e.g. show it on screen \ save it etc

![image](https://user-images.githubusercontent.com/10872799/76120875-53bb6f00-5fea-11ea-88eb-78a708d1bc3a.png)
