### ISSUE TITLE
Minimized window

### ISSUE THREAD

**Issue by splendid25** [tjscience/RoboSharp#74]
Hi, when start from a WinForms app, Robocopy.exe is display in a normal window on top of the current form.
Is is possible to start Robocopy.exe minimized ?

**Comment by bruceburge** [comment]
Please post the code of how you are using robosharp, in my experience there is no window created.

**Comment by splendid25** [comment]
Sure here it is :
```c#
using (var copyCommand = new RoboCommand())
{
    copyCommand.CopyOptions.Source = originalPath;
    copyCommand.CopyOptions.Destination = targetPath;
    copyCommand.CopyOptions.CopySubdirectories = true;

    copyCommand.RetryOptions.RetryCount = 1;
    copyCommand.RetryOptions.RetryWaitTime = 2;

    var task = copyCommand.Start(domain, user, pwd);
    task.Wait();
}
```

It seems the window is displayed on the task.Wait().
I use RoboCopy from a .NET4.0 Winform App. Is there another way to wait synchronously ?

Thanks

**Comment by splendid25** [comment]
OK I found details on the issue.
If I run this there is no window :
```c#
var task = copyCommand.Start();
```
And with another user running robocopy, a console window appears, with the title 'C:\Windows\system32\Robocopy.exe' :
```c#
var task = copyCommand.Start(domain, user, pwd);
```

In my use case, the user running the program won't have permissions to access the folders, so I need to  run Robocopy as another user.
