### ISSUE TITLE
RoboSharp does not support net 4.0

### ISSUE THREAD

**Issue by filippobottega** [tjscience/RoboSharp#75]
Hello,
  installing RoboSharp v1.2.0 on a project targeting .NET Framework 4.0 I get the error:

`Non è stato possibile installare il pacchetto 'System.Management 4.5.0'. Si sta tentando di eseguire l'installazione in un progetto destinato a '.NETFramework,Version=v4.0', ma il pacchetto non contiene riferimenti ad assembly o file di dati compatibili con il framework. Per altre informazioni, contattare l'autore del pacchetto.	`

  Google translation:

`The 'System.Management 4.5.0' package could not be installed. You are attempting to install in a project intended for '.NETFramework, Version = v4.0', but the package does not contain assembly references or data files compatible with the framework. For more information, contact the author of the package.`

  Do I have to install a previous version?

  Thank you and best regards,
    Filippo

**Comment by wingers999** [comment]
@filippobottega - just tested v1.2.1 of RoboSharp both from GitHub and via NuGet and it worked perfectly fine with an app targeting .NET Framework 4.0.  I didn't have any issues like you reported above.  If you continue to have problems then please report back and we can reopen this issue and diagnose further.  Thanks
