### ISSUE TITLE
Win32Exception: The directory name is invalid

### ISSUE THREAD

**Issue by splendid25** [tjscience/RoboSharp#76]
I use RoboSharp by specifying domain, user, and password.

I have an issue when the executable is inside a user protected folder c:\users\myuser\...
This error occurs : Win32Exception: The directory name is invalid

I tried to modifiy existing code by adding WorkingDirectory and it seems OK now :
```csharp
Debugger.Instance.DebugMessage("Setting RoboCopy process up...");
process.StartInfo.UseShellExecute = false;
process.StartInfo.WorkingDirectory = Environment.GetFolderPath(Environment.SpecialFolder.System);
```

Is there any Test project to verify it doesn't brake anything else?

**Comment by bruceburge** [comment]
I believe there is other factors at play here,

If you read the spec on process start working directory

You'll see

```
 The WorkingDirectory property must be set if UserName and Password are provided. If the property is not set, the default working directory is %SYSTEMROOT%\system32.

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.workingdirectory?redirectedfrom=MSDN&view=netframework-4.7.2#System_Diagnostics_ProcessStartInfo_WorkingDirectory
```

It seems that not providing a working directory with user/pass will default to one, I am unsure if the 32 resolves to somewhere different on the machine you are running than the default but you may want to check that also. 
Have you attempted to run robocopy command from the command line using your same parameters

**Comment by splendid25** [comment]
Yes, UseShellExecute was already set to false in the trunk : 
https://github.com/tjscience/RoboSharp/blob/5ba31794de8a8ee81a5b562fc25dd3293b424093/RoboSharp/RoboCommand.cs#L256

> When UseShellExecute is true, the fully qualified name of the directory that contains the process to be started. When the UseShellExecute property is false, the working directory for the process to be started.

It definitely has something to do with this, but I don't know the best way to solve it.

The original RoboCommand :
- works correctly when started from C:\Sources.
- crashes when started from C:\Users\myUser.myDomain

With .WorkingDirectory manually set to system32 :
- works anywhere

And this command line works :
`C:\Users\myUser.myDomain>runas /user:myDomain\otherUser "robocopy \\remote\c$\a\ \\remote\c$\b\"`

**Comment by bruceburge** [comment]
have you turned on logging? does the output of that provide the exact issue? 
sorry I'm needing so much leg work from you on this, I'm not at a spot where I can test the code myself. 

`RoboCom.LoggingOptions.OutputToRoboSharpAndLog = true;`

**Comment by splendid25** [comment]
Here is the StackTrace :
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.ComponentModel.Win32Exception: Nom de répertoire non valide
   à System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   à RoboSharp.RoboCommand.<>c__DisplayClass52_0.<Start>b__0() dans C:\Sources\GProd_trunk\RoboSharp\RoboCommand.cs:ligne 268

It fails before the internal logging happens, the log file is not created.


I tried to set UseShellExecute to false, but it is mandatory when executing process as another user.

**Comment by splendid25** [comment]
I managed to make it work without modifying RoboCommand, by doing this :

```csharp
var prevWorking = Environment.CurrentDirectory;
try
{
    Environment.CurrentDirectory = Environment.GetFolderPath(Environment.SpecialFolder.System);

    var task = copyCommand.Start(myDomain, myUser, myPassword);
    task.Wait();
}
finally
{
    Environment.CurrentDirectory = prevWorking;
}
```
