### ISSUE TITLE
LoggingFolder does not allow spaces in path

### ISSUE THREAD

**Issue by andygadget** [tjscience/RoboSharp#77]
using the .LoggingOptions.LogPath="C:\TEMP\My Folder\logfile.txt" causes the process to fail.
In loggingOptions.cs I can prevent this hapenning using
        internal const string LOG_PATH = "/LOG:\"{0}\" ";
        internal const string APPEND_LOG_PATH = "/LOG+:\"{0}\" ";
to quote the log path(s) but not sure this is an optimal solution
I have not added this to the repo

**Comment by wingers999** [comment]
Hi

Agreed that current LoggingOptions.LogPath settings do not work well with spaces in path and would need changing as below e.g. adding quotes around path which would need to be escaped with \ to be valid code

 ```
       internal const string LOG_PATH = "/LOG:\"{0}\" ";
        internal const string APPEND_LOG_PATH = "/LOG+:\"{0}\" ";
        internal const string UNICODE_LOG_PATH = "/UNILOG:\"{0}\" ";
        internal const string APPEND_UNICODE_LOG_PATH = "/UNILOG+:\"{0}\" ";
```

BUT with the new commit in dev branch, ExtendedResults have been added so you can access the contents of the log file as shown below (e.Results.LogLines) and then you can choose what you wish to do with it e.g. show it on screen \ save it etc.  And this means that the above LOG_PATH variables are no longer needed and in fact if used can cause the ExtendedResults code to not work correctly

![image](https://user-images.githubusercontent.com/10872799/76120737-08a15c00-5fea-11ea-9358-13c35c76e8d7.png)

Therefore I am closing this issue for now as it has an alternative working solution
