### ISSUE TITLE
Sample Code does not match nuget version.

### ISSUE THREAD

**Issue by ArdAtak** [tjscience/RoboSharp#89]
I appears that the changes made in the dev branch did not make their way to the master branch.  The sample code on main page, specifically having to do with the "Results" property of the "RoboCommandCompletedEventArgs" class generates errors since that property does not exist on the master branch.

**Comment by wingers999** [comment]
Hi ArdAtak, yes lots of improvements and changes were added to the dev branch which are not yet in the master branch.  The documentation relating to the new features of the Results property will only work if you are using the dev branch (which is the most up to date for now)

**Comment by wingers999** [comment]
@tjscience - can I suggest we move the dev branch to master now so that all the new features and improvements can be pushed to a new nuget release?

**Comment by tjscience** [comment]
dev has been merged into master.

**Comment by wingers999** [comment]
Excellent, thank you :) - hopefully a new NuGet version can be released from master

**Comment by tjscience** [comment]
Yes, pushed.

**Comment by PCAssistSoftware** [comment]
Thanks Terry

**Comment by ArdAtak** [comment]
Thanks!
