### ISSUE TITLE
No Event fire when 

### ISSUE THREAD

**Issue by Onthelees** [tjscience/RoboSharp#96]
I have been poking around here, reading the issues and I can't find anything about this. My event handlers never get called, under any circumstances. I have OnFileProcessed, OnCommandCompleted, and OnError defined. If there is an exception, I get no logging in addition to no events being fired. I am running an NUnit test inside VS2017 if that has anything to do with it. I must be doing something wrong?

Here the code: 

 public void RemoteTest()
      {
         var SourcePath = @"<some source Directory>";
         var DestinationPath = @"< some destination Directory>";
         using (var robo = new RoboCommand())
         {

            robo.OnFileProcessed += cmd_OnFileProcessed;
            robo.OnCommandCompleted += cmd_OnCommandCompleted;
            robo.OnError += cmd_OnError;
            //// copy options
            robo.CopyOptions.Source = SourcePath;
            robo.CopyOptions.Destination = DestinationPath;
            robo.CopyOptions.CopySubdirectories = false;
            robo.CopyOptions.UseUnbufferedIo = true;
            robo.LoggingOptions.OutputToRoboSharpAndLog = true;
            robo.LoggingOptions.IncludeFullPathNames = true;
            robo.LoggingOptions.LogPath = @"<some path>\RoboLog.log";
            robo.LoggingOptions.IncludeSourceTimeStamps = true;
            robo.RetryOptions.RetryCount = 3;
            robo.RetryOptions.RetryWaitTime = 30;
            Console.WriteLine(robo.Configuration.ErrorToken);
            Console.WriteLine(robo.Configuration.RoboCopyExe);
            Console.WriteLine(robo.CommandOptions);
            robo.Start()?.ContinueWith((p) =>
            {
               if (robo != null)
               {
                  robo.OnError -= cmd_OnError;
                  robo.OnCommandCompleted -= cmd_OnCommandCompleted;
                  robo.OnFileProcessed -= cmd_OnFileProcessed;
               }
            });
         }
      }

      private void cmd_OnFileProcessed(object sender, FileProcessedEventArgs e)
      {
         Console.WriteLine(e.ProcessedFile.Name);
      }

      void cmd_OnCommandCompleted(object sender, RoboCommandCompletedEventArgs e)
      {
         var results = e.Results;
         Console.WriteLine("Files copied: " + results.FilesStatistic.Copied);
         Console.WriteLine("Directories copied: " + results.DirectoriesStatistic.Copied);
         Console.WriteLine("MegaBytesPerMin: " + results.SpeedStatistic.MegaBytesPerMin);
      }

      void cmd_OnError(object sender, ErrorEventArgs e)
      {
         Console.WriteLine(string.Format("{0}:{1}", e.ErrorCode, e.Error));
      }

**Comment by tjscience** [comment]
robo.Start() runs asynchronously, and it looks like you are not awaiting the operation.

**Comment by Onthelees** [comment]
Ah - I suspected that might be the case, but your example showed just cmd.start(), so I thought it might be possible.
